import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ru' | 'ar' | 'uk' | 'de' | 'zh' | 'pt' | 'es' | 'vi' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const baseTranslations: Record<string, string> = {
  settings: 'Settings',
  my_uid: 'My UID',
  language: 'Language',
  contact_support: 'Contact Support',
  legal_info: 'Legal Information',
  terms_conditions: 'Terms & Conditions',
  privacy_policy: 'Privacy Policy',
  acceptable_use: 'Acceptable Use Policy',
  copied: 'Copied to clipboard!',
  close: 'Close',
  english: 'English',
  russian: 'Russian',
  arabic: 'Arabic',
  admin_panel: 'Admin Panel',
  back: 'Back',
  home: 'HOME',
  rank: 'RANK',
  invite: 'INVITE',
  mission: 'MISSION',
  admin: 'ADMIN',
  balance: 'BALANCE',
  withdraw_upper: 'WITHDRAW',
  swap: 'SWAP',
  weekly_contest: 'Weekly Contest',
  top_earners: 'Top Inviters',
  take_the_prize: 'Take the Prize',
  prize_pool: 'Pool Prize',
  income_statistics: 'INCOME STATISTICS',
  today: 'Today',
  weekly: 'Weekly',
  monthly: 'Monthly',
  all_time: 'All-Time',
  streak: 'Streak',
  days: 'days',
  watch_ads: 'Watch Ads',
  earn_pow: 'Earn POW',
  daily_limit: 'Daily Limit',
  watch: 'Watch',
  watching: 'Watching...',
  claim: 'Claim',
  claimed: 'Claimed',
  viewing_ads: 'Viewing Ads',
  get_paid_watching: 'Get paid for watching short Ads on Telegram.',
  start_earning: 'Start Earning',
  loading_ad: 'Loading Ad...',
  verifying: 'Verifying...',
  daily_limit_reached_tomorrow: 'Daily limit reached. Resets tomorrow.',
  hourly_limit_reached: 'Hourly limit reached. Refills in ~1 hour.',
  ads_available_label: 'ads available',
  today_label: 'today',
  affiliates: 'Affiliates',
  affiliates_program: 'Affiliates Program',
  we_pay_out: 'We pay out up to',
  from_l1_income: 'from the income of referrals of the 1st level and up to',
  from_l2_income: 'from the income of referrals of the 2nd level.',
  copy: 'COPY',
  level1_referrals: 'Level 1 Referrals',
  of_friends_pow: 'of your friends POW',
  from_their_friends: 'from their friends',
  get_label: 'Get',
  level2_referrals: 'Level 2 Referrals',
  bonus: 'Bonus',
  when_friend_watches: 'When your friend watches 1 ad',
  disabled: 'Disabled',
  total_affiliate_earnings: 'Total Affiliate Earnings',
  usd_earned: 'USD Earned',
  total_from_referrals: 'Total from all referrals',
  pow_earned: 'POW Earned',
  total_pow_l1: 'Total POW from L1 commissions',
  link_copied: 'Link copied!',
  referral_link: 'Referral Link',
  copy_link: 'Copy Link',
  friends_invited: 'Friends Invited',
  total_earned: 'Total Earned',
  invite_friends: 'Invite Friends',
  how_it_works: 'How It Works',
  withdraw: 'Withdraw',
  withdrawal: 'Withdrawal',
  amount: 'Amount',
  wallet_address: 'Wallet Address',
  submit: 'Submit',
  minimum: 'Minimum',
  available: 'Available',
  history: 'History',
  pending: 'Pending',
  completed: 'Completed',
  rejected: 'Rejected',
  checking_requirements: 'Checking requirements...',
  pending_withdrawal_warning: 'You have a pending withdrawal. Please wait for it to be processed.',
  select_withdrawal_package: 'Select Withdrawal Package',
  full_balance: 'FULL BALANCE',
  you_will_receive: 'You will receive',
  withdrawal_method: 'Withdrawal method',
  to_withdraw_need: 'To withdraw you need:',
  wallet_activity: 'Wallet Activity',
  no_transactions_yet: 'No transactions yet',
  withdrawal_history_here: 'Your withdrawal history will appear here',
  connect: 'Connect',
  fee_label: 'fee',
  select_package: 'Select a Package',
  insufficient_balance: 'Insufficient Balance',
  requirements_not_met: 'Requirements Not Met',
  withdrawal_request_sent: 'You have sent a withdrawal request.',
  friends: 'friends',
  friend: 'friend',
  ads_count: 'ads',
  ad_count: 'ad',
  ads_watched_progress: 'ads watched',
  more_ads_to_watch: 'more to go',
  full_balance_lower: 'Full balance',
  via: 'via',
  enter_withdrawal_amount: 'Enter Withdrawal Amount',
  withdraw_balance: 'Withdraw Balance',
  missions: 'Missions',
  mission_title: 'Mission',
  complete_tasks_earn: 'Complete tasks and earn POW rewards',
  promo_code_label: 'Promo Code',
  earn_with_ads: 'Earn with ADS',
  all_tasks_label: 'All Tasks',
  all_tab: 'All',
  daily_tab: 'Daily',
  partner_tab: 'Partner',
  no_tasks_available: 'No tasks available right now',
  come_back_tomorrow: 'come back tomorrow',
  no_ad_available: 'No ad available right now, try again later',
  watch_full_ad: 'Please watch the full ad to earn',
  something_went_wrong: 'Something went wrong',
  coming_soon_label: 'Coming Soon',
  i_want_task_here: 'I want my task here',
  create_your_own_task: 'create your own task',
  done_label: 'DONE',
  watch_label: 'WATCH',
  channel_label: 'Channel',
  bot_website_label: 'Bot / Website',
  partner_label: 'Partner',
  claim_label: 'CLAIM',
  loading_ellipsis: 'Loading…',
  share_with_friends: 'Share with Friends',
  daily_checkin: 'Daily Check-in',
  check_for_updates: 'Check for Updates',
  reward: 'Reward',
  go: 'Go',
  share: 'Share',
  daily_limit_short: 'Daily limit reached',
  per_day: '/day',
  account_banned_msg: 'Your account has been banned due to suspicious multi-account activity',
  ban_details: 'Details:',
  all_features_disabled: 'All features are disabled. If you believe this is a mistake, please contact our',
  support_team: 'support team',
  admin_self_unban: 'Admin Self-Unban',
  unbanned_successfully: 'Successfully unbanned! Reloading...',
  not_available: 'Not Available',
  not_available_country: 'This app is not available in your country.',
  join_required: '🔒 Join Required',
  join_required_desc: 'To continue using PaidAdz, you must join our official Channel and Community Group.',
  join_channel: '📢 Join Channel',
  join_group: '💬 Join Group',
  verify_membership: '✅ Verify Membership',
  not_member_yet: 'Please join both the channel and group first, then tap Verify.',
  loading: 'Loading...',
  error: 'Error',
  retry: 'Retry',
  save: 'Save',
  cancel: 'Cancel',
  confirm: 'Confirm',
  success: 'Success',
  failed: 'Failed',
  processing: 'Processing...',
  select_language: 'Select Language',
  language_changed: 'Language changed!',

  // ── Navigation ──────────────────────────────────────────────────────────────
  nav_friends: 'Friends',
  nav_rank: 'Rank',

  // ── Ad watching section ─────────────────────────────────────────────────────
  daily_adz: 'Daily Adz',
  premium_adz: 'Premium Adz',
  limit_reached: 'Limit Reached',
  get_pow: 'Get POW',
  sponsored_by: 'Sponsored by',
  ad_limit: 'Ad Limit',

  // ── Leaderboard ─────────────────────────────────────────────────────────────
  monthly_contest: 'Monthly Contest',
  referral_contest_label: 'Referral Contest',
  updates_30s: 'Updates every 30 seconds',
  your_rank: 'Your Rank',
  started: 'Started',
  ends: 'Ends',
  time_left: 'Time left:',
  contest_not_active: 'Contest Not Active',
  monthly_contest_soon: 'Admin will start the next Monthly Contest soon.',
  referral_contest_soon: 'Admin will start the next Referral Contest soon.',
  you_label: 'You',
  rankings: 'Rankings',
  pos_label: 'POS',
  name_label: 'NAME',
  stars_label: 'STARS',
  refs_label: 'REFS',
  verified_label: 'verified',
  monthly_tab: 'Monthly',
  referral_tab: 'Referral',
  available_now: 'Available now',
  stars: 'stars',
  watch_ads_climb: 'Watch ads to earn stars and climb!',
  invite_friends_rank: 'Invite friends who watch 1+ ad to rank up!',

  // ── Withdraw ─────────────────────────────────────────────────────────────────
  disconnect_wallet: 'Disconnect wallet',
  guest_label: 'Guest',

  // ── Advertiser task sheet ────────────────────────────────────────────────────
  open_bot_title: 'Open Bot & Start It',
  open_bot_start_body: 'Open the bot via the referral link and press Start to activate it.',
  copy_referral_title: 'Copy Your Referral Link',
  copy_referral_body: 'Inside the bot, go to Invite Friends → Copy your unique referral link.',
  ive_copied_link: "I've Copied the Link →",
  paste_referral_title: 'Paste Your Referral Link',
  paste_referral_body: 'Paste the referral link you copied from the bot.',
  paste_referral_placeholder: 'Paste your referral link here',
  invalid_referral_link: 'Invalid referral link. Please paste the correct link from the bot.',
  skip: 'Skip',
  verify_and_claim: 'Verify & Claim',
  join_the_channel_task: 'Join the Channel',
  join_channel_task_body: "Open the channel and join. Then tap 'Verify Membership' — the bot checks automatically.",
  open_channel: 'Open Channel',
  open_bot: 'Open Bot',
  checking_ellipsis: 'Checking...',
  looking_for_referrals: 'Looking for referrals',
  looking_for_subscribers: 'Looking for subscribers',
  channel_penalty_text: 'Important: Leaving this channel within 7 days will result in a 50,000 POW penalty deducted automatically.',
  open_the_bot: 'Open the Bot',
  open_bot_instant_body: 'Press Start inside the bot — your reward is granted instantly.',
  open_the_channel: 'Open the Channel',
  open_channel_instant_body: 'Join the channel — your reward is granted instantly.',
  havent_joined_channel: "You haven't joined the channel yet.",
  network_error_retry: 'Network error. Please try again.',

  // ── Home notifications ───────────────────────────────────────────────────────
  no_pow_to_swap: 'No POW balance to swap.',
  watch_ad_for_bonus: 'Please watch the ad completely to claim your bonus.',
  failed_claim_streak_retry: 'Failed to claim streak. Please try again.',
  enter_promo_code: 'Please enter a promo code',
  watch_ad_for_promo: 'Please watch the ad to claim your promo code.',
  task_started_msg: 'Task started! Click the claim button to earn your reward.',
  join_channel_complete: 'Please join the channel to complete this task.',
  convert_successful: 'Convert successful.',
};

const translations: Record<Language, Record<string, string>> = {
  en: baseTranslations,

  ru: {
    ...baseTranslations,
    settings: 'Настройки',
    my_uid: 'Мой UID',
    language: 'Язык',
    contact_support: 'Поддержка',
    legal_info: 'Юридическая информация',
    terms_conditions: 'Условия и положения',
    privacy_policy: 'Политика конфиденциальности',
    acceptable_use: 'Правила использования',
    copied: 'Скопировано!',
    close: 'Закрыть',
    english: 'Английский',
    russian: 'Русский',
    arabic: 'Арабский',
    admin_panel: 'Панель администратора',
    back: 'Назад',
    home: 'ГЛАВНАЯ',
    rank: 'РЕЙТИНГ',
    invite: 'ПРИГЛАСИТЬ',
    mission: 'ЗАДАНИЯ',
    admin: 'ADMIN',
    balance: 'БАЛАНС',
    withdraw_upper: 'ВЫВОД',
    swap: 'ОБМЕН',
    weekly_contest: 'Еженедельный конкурс',
    top_earners: 'Лучшие партнёры',
    take_the_prize: 'Забери приз',
    prize_pool: 'Призовой фонд',
    income_statistics: 'СТАТИСТИКА ДОХОДА',
    today: 'Сегодня',
    weekly: 'За неделю',
    monthly: 'За месяц',
    all_time: 'За всё время',
    streak: 'Серия',
    days: 'дней',
    watch_ads: 'Смотреть рекламу',
    earn_pow: 'Заработать POW',
    daily_limit: 'Дневной лимит',
    watch: 'Смотреть',
    watching: 'Просмотр...',
    claim: 'Получить',
    claimed: 'Получено',
    viewing_ads: 'Просмотр рекламы',
    get_paid_watching: 'Получайте деньги за просмотр коротких реклам в Telegram.',
    start_earning: 'Начать зарабатывать',
    loading_ad: 'Загрузка рекламы...',
    verifying: 'Проверяем...',
    daily_limit_reached_tomorrow: 'Дневной лимит исчерпан. Сбросится завтра.',
    hourly_limit_reached: 'Часовой лимит исчерпан. Обновится через ~1 час.',
    ads_available_label: 'реклам доступно',
    today_label: 'сегодня',
    affiliates: 'Партнёры',
    affiliates_program: 'Партнёрская программа',
    we_pay_out: 'Мы выплачиваем до',
    from_l1_income: 'от дохода рефералов 1-го уровня и до',
    from_l2_income: 'от дохода рефералов 2-го уровня.',
    copy: 'КОПИРОВАТЬ',
    level1_referrals: 'Рефералы 1-го уровня',
    of_friends_pow: 'от POW ваших друзей',
    from_their_friends: 'от доходов их друзей',
    get_label: 'Получайте',
    level2_referrals: 'Рефералы 2-го уровня',
    bonus: 'Бонус',
    when_friend_watches: 'Когда ваш друг посмотрит 1 рекламу',
    disabled: 'Отключено',
    total_affiliate_earnings: 'Всего заработано с партнёров',
    usd_earned: 'Заработано USD',
    total_from_referrals: 'Итого от всех рефералов',
    pow_earned: 'Заработано POW',
    total_pow_l1: 'Всего POW от комиссий L1',
    link_copied: 'Ссылка скопирована!',
    referral_link: 'Реферальная ссылка',
    copy_link: 'Копировать ссылку',
    friends_invited: 'Приглашено друзей',
    total_earned: 'Всего заработано',
    invite_friends: 'Пригласить друзей',
    how_it_works: 'Как это работает',
    withdraw: 'Вывод',
    withdrawal: 'Вывод средств',
    amount: 'Сумма',
    wallet_address: 'Адрес кошелька',
    submit: 'Отправить',
    minimum: 'Минимум',
    available: 'Доступно',
    history: 'История',
    pending: 'В обработке',
    completed: 'Завершено',
    rejected: 'Отклонено',
    checking_requirements: 'Проверка условий...',
    pending_withdrawal_warning: 'У вас есть незавершённый вывод. Пожалуйста, дождитесь его обработки.',
    select_withdrawal_package: 'Выберите сумму вывода',
    full_balance: 'ВЕСЬ БАЛАНС',
    you_will_receive: 'Вы получите',
    withdrawal_method: 'Способ вывода',
    to_withdraw_need: 'Для вывода необходимо:',
    wallet_activity: 'Активность кошелька',
    no_transactions_yet: 'Транзакций пока нет',
    withdrawal_history_here: 'История ваших выводов появится здесь',
    connect: 'Подключить',
    fee_label: 'комиссия',
    select_package: 'Выберите пакет',
    insufficient_balance: 'Недостаточно средств',
    requirements_not_met: 'Условия не выполнены',
    withdrawal_request_sent: 'Запрос на вывод отправлен.',
    friends: 'друзей',
    friend: 'друга',
    ads_count: 'реклам',
    ad_count: 'реклама',
    ads_watched_progress: 'реклам просмотрено',
    more_ads_to_watch: 'осталось',
    full_balance_lower: 'Весь баланс',
    via: 'через',
    enter_withdrawal_amount: 'Введите сумму вывода',
    withdraw_balance: 'Вывод баланса',
    missions: 'Задания',
    mission_title: 'Задания',
    complete_tasks_earn: 'Выполняйте задания и зарабатывайте POW',
    promo_code_label: 'Промокод',
    earn_with_ads: 'Заработок с РЕКЛАМОЙ',
    all_tasks_label: 'Все задания',
    all_tab: 'Все',
    daily_tab: 'Ежедневные',
    partner_tab: 'Партнёры',
    no_tasks_available: 'Сейчас нет доступных заданий',
    come_back_tomorrow: 'возвращайтесь завтра',
    no_ad_available: 'Реклама недоступна, попробуйте позже',
    watch_full_ad: 'Пожалуйста, досмотрите рекламу до конца',
    something_went_wrong: 'Что-то пошло не так',
    coming_soon_label: 'Скоро',
    i_want_task_here: 'Хочу разместить задание здесь',
    create_your_own_task: 'создайте своё задание',
    done_label: 'ГОТОВО',
    watch_label: 'СМОТРЕТЬ',
    channel_label: 'Канал',
    bot_website_label: 'Бот / Сайт',
    partner_label: 'Партнёр',
    claim_label: 'ПОЛУЧИТЬ',
    loading_ellipsis: 'Загрузка…',
    share_with_friends: 'Поделиться с друзьями',
    daily_checkin: 'Ежедневный вход',
    check_for_updates: 'Проверить обновления',
    reward: 'Награда',
    go: 'Перейти',
    share: 'Поделиться',
    daily_limit_short: 'Дневной лимит исчерпан',
    per_day: '/день',
    account_banned_msg: 'Ваш аккаунт заблокирован из-за подозрительной активности с несколькими аккаунтами',
    ban_details: 'Подробности:',
    all_features_disabled: 'Все функции отключены. Если вы считаете, что это ошибка, свяжитесь с нашей',
    support_team: 'службой поддержки',
    admin_self_unban: 'Разблокировать (Админ)',
    unbanned_successfully: 'Разблоковано! Перезагрузка...',
    not_available: 'Недоступно',
    not_available_country: 'Это приложение недоступно в вашей стране.',
    join_required: '🔒 Требуется вступление',
    join_required_desc: 'Чтобы продолжить использование PaidAdz, вы должны вступить в наш официальный канал и группу сообщества.',
    join_channel: '📢 Вступить в канал',
    join_group: '💬 Вступить в группу',
    verify_membership: '✅ Подтвердить членство',
    not_member_yet: 'Сначала вступите в канал и группу, затем нажмите «Подтвердить».',
    loading: 'Загрузка...',
    error: 'Ошибка',
    retry: 'Повторить',
    save: 'Сохранить',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    success: 'Успешно',
    failed: 'Не удалось',
    processing: 'Обработка...',
    select_language: 'Выберите язык',
    language_changed: 'Язык изменён!',
  },

  ar: {
    ...baseTranslations,
    settings: 'الإعدادات',
    my_uid: 'معرّفي',
    language: 'اللغة',
    contact_support: 'التواصل مع الدعم',
    legal_info: 'المعلومات القانونية',
    terms_conditions: 'الشروط والأحكام',
    privacy_policy: 'سياسة الخصوصية',
    acceptable_use: 'سياسة الاستخدام المقبول',
    copied: 'تم النسخ!',
    close: 'إغلاق',
    english: 'الإنجليزية',
    russian: 'الروسية',
    arabic: 'العربية',
    admin_panel: 'لوحة الإدارة',
    back: 'رجوع',
    home: 'الرئيسية',
    rank: 'الترتيب',
    invite: 'دعوة',
    mission: 'المهام',
    admin: 'مدير',
    balance: 'الرصيد',
    withdraw_upper: 'سحب',
    swap: 'تحويل',
    weekly_contest: 'مسابقة الأسبوع',
    top_earners: 'أعلى المكتسبين',
    take_the_prize: 'يفوزون بالجائزة',
    prize_pool: 'مجموع الجوائز',
    income_statistics: 'إحصائيات الدخل',
    today: 'اليوم',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    all_time: 'كل الوقت',
    streak: 'التسلسل',
    days: 'أيام',
    watch_ads: 'مشاهدة الإعلانات',
    earn_pow: 'اكسب POW',
    daily_limit: 'الحد اليومي',
    watch: 'شاهد',
    watching: 'جارٍ المشاهدة...',
    claim: 'استلام',
    claimed: 'تم الاستلام',
    viewing_ads: 'مشاهدة الإعلانات',
    get_paid_watching: 'احصل على أموال مقابل مشاهدة إعلانات قصيرة على تيليغرام.',
    start_earning: 'ابدأ الكسب',
    loading_ad: 'جارٍ تحميل الإعلان...',
    verifying: 'جارٍ التحقق...',
    daily_limit_reached_tomorrow: 'تم بلوغ الحد اليومي. يُعاد ضبطه غداً.',
    hourly_limit_reached: 'تم بلوغ الحد الساعي. يتجدد خلال ساعة.',
    ads_available_label: 'إعلانات متاحة',
    today_label: 'اليوم',
    affiliates: 'الشركاء',
    affiliates_program: 'برنامج الشراكة',
    we_pay_out: 'ندفع حتى',
    from_l1_income: 'من دخل الإحالات من المستوى الأول وحتى',
    from_l2_income: 'من دخل الإحالات من المستوى الثاني.',
    copy: 'نسخ',
    level1_referrals: 'إحالات المستوى الأول',
    of_friends_pow: 'من POW أصدقائك',
    from_their_friends: 'من أصدقائهم',
    get_label: 'احصل على',
    level2_referrals: 'إحالات المستوى الثاني',
    bonus: 'مكافأة',
    when_friend_watches: 'عندما يشاهد صديقك إعلاناً واحداً',
    disabled: 'معطّل',
    total_affiliate_earnings: 'إجمالي أرباح الشراكة',
    usd_earned: 'USD مكتسب',
    total_from_referrals: 'الإجمالي من جميع الإحالات',
    pow_earned: 'POW مكتسب',
    total_pow_l1: 'إجمالي POW من عمولات L1',
    link_copied: 'تم نسخ الرابط!',
    referral_link: 'رابط الإحالة',
    copy_link: 'نسخ الرابط',
    friends_invited: 'الأصدقاء المدعوون',
    total_earned: 'إجمالي المكتسب',
    invite_friends: 'دعوة الأصدقاء',
    how_it_works: 'كيف يعمل',
    withdraw: 'سحب',
    withdrawal: 'السحب',
    amount: 'المبلغ',
    wallet_address: 'عنوان المحفظة',
    submit: 'إرسال',
    minimum: 'الحد الأدنى',
    available: 'متاح',
    history: 'السجل',
    pending: 'قيد الانتظار',
    completed: 'مكتمل',
    rejected: 'مرفوض',
    checking_requirements: 'جارٍ التحقق من المتطلبات...',
    pending_withdrawal_warning: 'لديك سحب معلق. يرجى الانتظار حتى تتم معالجته.',
    select_withdrawal_package: 'اختر حزمة السحب',
    full_balance: 'الرصيد الكامل',
    you_will_receive: 'ستستلم',
    withdrawal_method: 'طريقة السحب',
    to_withdraw_need: 'للسحب تحتاج:',
    wallet_activity: 'نشاط المحفظة',
    no_transactions_yet: 'لا توجد معاملات بعد',
    withdrawal_history_here: 'سيظهر سجل سحوباتك هنا',
    connect: 'اتصال',
    fee_label: 'رسوم',
    select_package: 'اختر حزمة',
    insufficient_balance: 'رصيد غير كافٍ',
    requirements_not_met: 'المتطلبات غير مستوفاة',
    withdrawal_request_sent: 'تم إرسال طلب السحب.',
    friends: 'أصدقاء',
    friend: 'صديق',
    ads_count: 'إعلانات',
    ad_count: 'إعلان',
    ads_watched_progress: 'إعلانات تمت مشاهدتها',
    more_ads_to_watch: 'متبقية',
    full_balance_lower: 'الرصيد الكامل',
    via: 'عبر',
    enter_withdrawal_amount: 'أدخل مبلغ السحب',
    withdraw_balance: 'سحب الرصيد',
    missions: 'المهام',
    mission_title: 'المهام',
    complete_tasks_earn: 'أكمل المهام واكسب مكافآت POW',
    promo_code_label: 'رمز ترويجي',
    earn_with_ads: 'اكسب مع الإعلانات',
    all_tasks_label: 'جميع المهام',
    all_tab: 'الكل',
    daily_tab: 'يومي',
    partner_tab: 'الشركاء',
    no_tasks_available: 'لا توجد مهام متاحة الآن',
    come_back_tomorrow: 'عُد غداً',
    no_ad_available: 'لا يوجد إعلان متاح الآن، حاول لاحقاً',
    watch_full_ad: 'يرجى مشاهدة الإعلان كاملاً للكسب',
    something_went_wrong: 'حدث خطأ ما',
    coming_soon_label: 'قريباً',
    i_want_task_here: 'أريد مهمتي هنا',
    create_your_own_task: 'أنشئ مهمتك الخاصة',
    done_label: 'تم',
    watch_label: 'شاهد',
    channel_label: 'قناة',
    bot_website_label: 'بوت / موقع',
    partner_label: 'شريك',
    claim_label: 'استلام',
    loading_ellipsis: 'جارٍ التحميل…',
    share_with_friends: 'شارك مع الأصدقاء',
    daily_checkin: 'تسجيل الدخول اليومي',
    check_for_updates: 'التحقق من التحديثات',
    reward: 'مكافأة',
    go: 'انتقل',
    share: 'شارك',
    daily_limit_short: 'تم بلوغ الحد اليومي',
    per_day: '/يوم',
    account_banned_msg: 'تم حظر حسابك بسبب نشاط مشبوه بحسابات متعددة',
    ban_details: 'التفاصيل:',
    all_features_disabled: 'جميع الميزات معطّلة. إذا كنت تعتقد أن هذا خطأ، يرجى التواصل مع',
    support_team: 'فريق الدعم',
    admin_self_unban: 'إلغاء الحظر (المشرف)',
    unbanned_successfully: 'تم إلغاء الحظر! جارٍ إعادة التحميل...',
    not_available: 'غير متاح',
    not_available_country: 'هذا التطبيق غير متاح في بلدك.',
    join_required: '🔒 الانضمام مطلوب',
    join_required_desc: 'لمواصلة استخدام PaidAdz، يجب عليك الانضمام إلى قناتنا الرسمية ومجموعة المجتمع.',
    join_channel: '📢 انضم إلى القناة',
    join_group: '💬 انضم إلى المجموعة',
    verify_membership: '✅ تحقق من العضوية',
    not_member_yet: 'يرجى الانضمام إلى القناة والمجموعة أولاً، ثم اضغط تحقق.',
    loading: 'جارٍ التحميل...',
    error: 'خطأ',
    retry: 'إعادة المحاولة',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    success: 'نجاح',
    failed: 'فشل',
    processing: 'جارٍ المعالجة...',
    select_language: 'اختر اللغة',
    language_changed: 'تم تغيير اللغة!',
  },

  uk: {
    ...baseTranslations,
    settings: 'Налаштування',
    my_uid: 'Мій UID',
    language: 'Мова',
    contact_support: 'Підтримка',
    legal_info: 'Юридична інформація',
    terms_conditions: 'Умови та положення',
    privacy_policy: 'Політика конфіденційності',
    acceptable_use: 'Правила використання',
    copied: 'Скопійовано!',
    close: 'Закрити',
    english: 'Англійська',
    russian: 'Російська',
    arabic: 'Арабська',
    admin_panel: 'Панель адміністратора',
    back: 'Назад',
    home: 'ГОЛОВНА',
    rank: 'РЕЙТИНГ',
    invite: 'ЗАПРОСИТИ',
    mission: 'ЗАВДАННЯ',
    admin: 'АДМІН',
    balance: 'БАЛАНС',
    withdraw_upper: 'ВИВЕДЕННЯ',
    swap: 'ОБМІН',
    weekly_contest: 'Тижневий конкурс',
    top_earners: 'Топ учасники',
    take_the_prize: 'беруть приз',
    prize_pool: 'Призовий фонд',
    income_statistics: 'СТАТИСТИКА ДОХОДІВ',
    today: 'Сьогодні',
    weekly: 'За тиждень',
    monthly: 'За місяць',
    all_time: 'За весь час',
    streak: 'Серія',
    days: 'днів',
    watch_ads: 'Дивитись рекламу',
    earn_pow: 'Заробити POW',
    daily_limit: 'Денний ліміт',
    watch: 'Дивитись',
    watching: 'Перегляд...',
    claim: 'Отримати',
    claimed: 'Отримано',
    viewing_ads: 'Перегляд реклами',
    get_paid_watching: 'Отримуйте гроші за перегляд коротких реклам у Telegram.',
    start_earning: 'Почати заробляти',
    loading_ad: 'Завантаження реклами...',
    verifying: 'Перевіряємо...',
    daily_limit_reached_tomorrow: 'Денний ліміт вичерпано. Скинеться завтра.',
    hourly_limit_reached: 'Годинний ліміт вичерпано. Оновиться за ~1 годину.',
    ads_available_label: 'реклам доступно',
    today_label: 'сьогодні',
    affiliates: 'Партнери',
    affiliates_program: 'Партнерська програма',
    we_pay_out: 'Ми виплачуємо до',
    from_l1_income: 'від доходу рефералів 1-го рівня та до',
    from_l2_income: 'від доходу рефералів 2-го рівня.',
    copy: 'КОПІЮВАТИ',
    level1_referrals: 'Реферали 1-го рівня',
    of_friends_pow: 'від POW ваших друзів',
    from_their_friends: 'від доходів їхніх друзів',
    get_label: 'Отримайте',
    level2_referrals: 'Реферали 2-го рівня',
    bonus: 'Бонус',
    when_friend_watches: 'Коли ваш друг переглядає 1 рекламу',
    disabled: 'Вимкнено',
    total_affiliate_earnings: 'Всього зароблено з партнерів',
    usd_earned: 'Зароблено USD',
    total_from_referrals: 'Разом від усіх рефералів',
    pow_earned: 'Зароблено POW',
    total_pow_l1: 'Всього POW від комісій L1',
    link_copied: 'Посилання скопійовано!',
    referral_link: 'Реферальне посилання',
    copy_link: 'Копіювати посилання',
    friends_invited: 'Запрошено друзів',
    total_earned: 'Всього зароблено',
    invite_friends: 'Запросити друзів',
    how_it_works: 'Як це працює',
    withdraw: 'Виведення',
    withdrawal: 'Виведення коштів',
    amount: 'Сума',
    wallet_address: 'Адреса гаманця',
    submit: 'Надіслати',
    minimum: 'Мінімум',
    available: 'Доступно',
    history: 'Історія',
    pending: 'В обробці',
    completed: 'Завершено',
    rejected: 'Відхилено',
    checking_requirements: 'Перевірка умов...',
    pending_withdrawal_warning: 'У вас є незавершений вивід. Будь ласка, дочекайтесь його обробки.',
    select_withdrawal_package: 'Виберіть суму виведення',
    full_balance: 'ВЕСЬ БАЛАНС',
    you_will_receive: 'Ви отримаєте',
    withdrawal_method: 'Спосіб виведення',
    to_withdraw_need: 'Для виведення потрібно:',
    wallet_activity: 'Активність гаманця',
    no_transactions_yet: 'Транзакцій поки немає',
    withdrawal_history_here: 'Ваша історія виведень з\'явиться тут',
    connect: 'Підключити',
    fee_label: 'комісія',
    select_package: 'Виберіть пакет',
    insufficient_balance: 'Недостатньо коштів',
    requirements_not_met: 'Умови не виконано',
    withdrawal_request_sent: 'Запит на виведення надіслано.',
    friends: 'друзів',
    friend: 'друга',
    ads_count: 'реклам',
    ad_count: 'реклама',
    ads_watched_progress: 'реклам переглянуто',
    more_ads_to_watch: 'залишилось',
    full_balance_lower: 'Весь баланс',
    via: 'через',
    enter_withdrawal_amount: 'Введіть суму виведення',
    withdraw_balance: 'Виведення балансу',
    missions: 'Завдання',
    mission_title: 'Завдання',
    complete_tasks_earn: 'Виконуйте завдання та заробляйте POW',
    promo_code_label: 'Промокод',
    earn_with_ads: 'Заробіток з РЕКЛАМОЮ',
    all_tasks_label: 'Всі завдання',
    all_tab: 'Всі',
    daily_tab: 'Щоденні',
    partner_tab: 'Партнери',
    no_tasks_available: 'Зараз немає доступних завдань',
    come_back_tomorrow: 'поверніться завтра',
    no_ad_available: 'Реклама недоступна, спробуйте пізніше',
    watch_full_ad: 'Будь ласка, перегляньте рекламу повністю',
    something_went_wrong: 'Щось пішло не так',
    coming_soon_label: 'Скоро',
    i_want_task_here: 'Хочу розмістити завдання тут',
    create_your_own_task: 'створіть власне завдання',
    done_label: 'ГОТОВО',
    watch_label: 'ДИВИТИСЬ',
    channel_label: 'Канал',
    bot_website_label: 'Бот / Сайт',
    partner_label: 'Партнер',
    claim_label: 'ОТРИМАТИ',
    loading_ellipsis: 'Завантаження…',
    share_with_friends: 'Поділитися з друзями',
    daily_checkin: 'Щоденний вхід',
    check_for_updates: 'Перевірити оновлення',
    reward: 'Нагорода',
    go: 'Перейти',
    share: 'Поділитися',
    daily_limit_short: 'Денний ліміт вичерпано',
    per_day: '/день',
    account_banned_msg: 'Ваш обліковий запис заблоковано через підозрілу активність з кількома обліковими записами',
    ban_details: 'Деталі:',
    all_features_disabled: 'Усі функції вимкнено. Якщо ви вважаєте, що це помилка, зверніться до нашої',
    support_team: 'служби підтримки',
    admin_self_unban: 'Розблокувати (Адмін)',
    unbanned_successfully: 'Розблоковано! Перезавантаження...',
    not_available: 'Недоступно',
    not_available_country: 'Цей додаток недоступний у вашій країні.',
    join_required: '🔒 Потрібно приєднатися',
    join_required_desc: 'Щоб продовжити використання PaidAdz, ви повинні приєднатися до нашого офіційного каналу та групи спільноти.',
    join_channel: '📢 Приєднатися до каналу',
    join_group: '💬 Приєднатися до групи',
    verify_membership: '✅ Підтвердити членство',
    not_member_yet: 'Спочатку приєднайтесь до каналу та групи, потім натисніть Підтвердити.',
    loading: 'Завантаження...',
    error: 'Помилка',
    retry: 'Повторити',
    save: 'Зберегти',
    cancel: 'Скасувати',
    confirm: 'Підтвердити',
    success: 'Успішно',
    failed: 'Не вдалося',
    processing: 'Обробка...',
    select_language: 'Виберіть мову',
    language_changed: 'Мову змінено!',
  },

  de: {
    ...baseTranslations,
    settings: 'Einstellungen',
    my_uid: 'Meine UID',
    language: 'Sprache',
    contact_support: 'Support kontaktieren',
    legal_info: 'Rechtliche Informationen',
    terms_conditions: 'Allgemeine Geschäftsbedingungen',
    privacy_policy: 'Datenschutzrichtlinie',
    acceptable_use: 'Nutzungsrichtlinie',
    copied: 'Kopiert!',
    close: 'Schließen',
    english: 'Englisch',
    russian: 'Russisch',
    arabic: 'Arabisch',
    admin_panel: 'Admin-Panel',
    back: 'Zurück',
    home: 'START',
    rank: 'RANG',
    invite: 'EINLADEN',
    mission: 'MISSION',
    admin: 'ADMIN',
    balance: 'GUTHABEN',
    withdraw_upper: 'ABHEBEN',
    swap: 'TAUSCHEN',
    weekly_contest: 'Wöchentlicher Wettbewerb',
    top_earners: 'Top-Verdiener',
    take_the_prize: 'gewinnen den Preis',
    prize_pool: 'Preispool',
    income_statistics: 'EINKOMMENSSTATISTIK',
    today: 'Heute',
    weekly: 'Wöchentlich',
    monthly: 'Monatlich',
    all_time: 'Gesamt',
    streak: 'Serie',
    days: 'Tage',
    watch_ads: 'Werbung ansehen',
    earn_pow: 'POW verdienen',
    daily_limit: 'Tageslimit',
    watch: 'Ansehen',
    watching: 'Schaue...',
    claim: 'Einfordern',
    claimed: 'Eingefordert',
    viewing_ads: 'Werbung ansehen',
    get_paid_watching: 'Werde bezahlt fürs Anschauen von kurzen Anzeigen auf Telegram.',
    start_earning: 'Jetzt verdienen',
    loading_ad: 'Werbung laden...',
    verifying: 'Überprüfen...',
    daily_limit_reached_tomorrow: 'Tageslimit erreicht. Setzt sich morgen zurück.',
    hourly_limit_reached: 'Stundenlimit erreicht. Erneuert sich in ~1 Stunde.',
    ads_available_label: 'Anzeigen verfügbar',
    today_label: 'heute',
    affiliates: 'Partner',
    affiliates_program: 'Partnerprogramm',
    we_pay_out: 'Wir zahlen bis zu',
    from_l1_income: 'vom Einkommen der Empfehlungen der 1. Ebene und bis zu',
    from_l2_income: 'vom Einkommen der Empfehlungen der 2. Ebene.',
    copy: 'KOPIEREN',
    level1_referrals: 'Empfehlungen Ebene 1',
    of_friends_pow: 'vom POW deiner Freunde',
    from_their_friends: 'von ihren Freunden',
    get_label: 'Erhalte',
    level2_referrals: 'Empfehlungen Ebene 2',
    bonus: 'Bonus',
    when_friend_watches: 'Wenn dein Freund 1 Werbung schaut',
    disabled: 'Deaktiviert',
    total_affiliate_earnings: 'Gesamte Partnereinnahmen',
    usd_earned: 'USD verdient',
    total_from_referrals: 'Gesamt von allen Empfehlungen',
    pow_earned: 'POW verdient',
    total_pow_l1: 'Gesamt POW aus L1-Provisionen',
    link_copied: 'Link kopiert!',
    referral_link: 'Empfehlungslink',
    copy_link: 'Link kopieren',
    friends_invited: 'Eingeladene Freunde',
    total_earned: 'Insgesamt verdient',
    invite_friends: 'Freunde einladen',
    how_it_works: 'Wie es funktioniert',
    withdraw: 'Abheben',
    withdrawal: 'Auszahlung',
    amount: 'Betrag',
    wallet_address: 'Wallet-Adresse',
    submit: 'Einreichen',
    minimum: 'Minimum',
    available: 'Verfügbar',
    history: 'Verlauf',
    pending: 'Ausstehend',
    completed: 'Abgeschlossen',
    rejected: 'Abgelehnt',
    checking_requirements: 'Anforderungen prüfen...',
    pending_withdrawal_warning: 'Du hast eine ausstehende Auszahlung. Bitte warte auf die Bearbeitung.',
    select_withdrawal_package: 'Auszahlungspaket wählen',
    full_balance: 'VOLLES GUTHABEN',
    you_will_receive: 'Du erhältst',
    withdrawal_method: 'Auszahlungsmethode',
    to_withdraw_need: 'Zum Abheben benötigst du:',
    wallet_activity: 'Wallet-Aktivität',
    no_transactions_yet: 'Noch keine Transaktionen',
    withdrawal_history_here: 'Deine Auszahlungshistorie erscheint hier',
    connect: 'Verbinden',
    fee_label: 'Gebühr',
    select_package: 'Paket auswählen',
    insufficient_balance: 'Unzureichendes Guthaben',
    requirements_not_met: 'Anforderungen nicht erfüllt',
    withdrawal_request_sent: 'Auszahlungsanfrage gesendet.',
    friends: 'Freunde',
    friend: 'Freund',
    ads_count: 'Anzeigen',
    ad_count: 'Anzeige',
    ads_watched_progress: 'Anzeigen angesehen',
    more_ads_to_watch: 'noch übrig',
    full_balance_lower: 'Volles Guthaben',
    via: 'über',
    enter_withdrawal_amount: 'Auszahlungsbetrag eingeben',
    withdraw_balance: 'Guthaben abheben',
    missions: 'Missionen',
    mission_title: 'Mission',
    complete_tasks_earn: 'Erledige Aufgaben und verdiene POW-Belohnungen',
    promo_code_label: 'Promo-Code',
    earn_with_ads: 'Mit WERBUNG verdienen',
    all_tasks_label: 'Alle Aufgaben',
    all_tab: 'Alle',
    daily_tab: 'Täglich',
    partner_tab: 'Partner',
    no_tasks_available: 'Keine Aufgaben verfügbar',
    come_back_tomorrow: 'komm morgen wieder',
    no_ad_available: 'Keine Werbung verfügbar, versuche es später',
    watch_full_ad: 'Bitte schau dir die ganze Werbung an, um zu verdienen',
    something_went_wrong: 'Etwas ist schiefgelaufen',
    coming_soon_label: 'Bald verfügbar',
    i_want_task_here: 'Ich möchte meine Aufgabe hier',
    create_your_own_task: 'erstelle deine eigene Aufgabe',
    done_label: 'FERTIG',
    watch_label: 'ANSEHEN',
    channel_label: 'Kanal',
    bot_website_label: 'Bot / Website',
    partner_label: 'Partner',
    claim_label: 'EINFORDERN',
    loading_ellipsis: 'Laden…',
    share_with_friends: 'Mit Freunden teilen',
    daily_checkin: 'Tägliches Einchecken',
    check_for_updates: 'Auf Updates prüfen',
    reward: 'Belohnung',
    go: 'Los',
    share: 'Teilen',
    daily_limit_short: 'Tageslimit erreicht',
    per_day: '/Tag',
    account_banned_msg: 'Dein Konto wurde wegen verdächtiger Multi-Account-Aktivität gesperrt',
    ban_details: 'Details:',
    all_features_disabled: 'Alle Funktionen sind deaktiviert. Wenn du glaubst, dass dies ein Fehler ist, kontaktiere unser',
    support_team: 'Support-Team',
    admin_self_unban: 'Entsperren (Admin)',
    unbanned_successfully: 'Entsperrt! Neuladen...',
    not_available: 'Nicht verfügbar',
    not_available_country: 'Diese App ist in deinem Land nicht verfügbar.',
    join_required: '🔒 Beitritt erforderlich',
    join_required_desc: 'Um PaidAdz weiter zu nutzen, musst du unserem offiziellen Kanal und der Community-Gruppe beitreten.',
    join_channel: '📢 Kanal beitreten',
    join_group: '💬 Gruppe beitreten',
    verify_membership: '✅ Mitgliedschaft bestätigen',
    not_member_yet: 'Bitte tritt zuerst dem Kanal und der Gruppe bei, dann tippe auf Bestätigen.',
    loading: 'Laden...',
    error: 'Fehler',
    retry: 'Wiederholen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    success: 'Erfolg',
    failed: 'Fehlgeschlagen',
    processing: 'Verarbeitung...',
    select_language: 'Sprache auswählen',
    language_changed: 'Sprache geändert!',
  },

  zh: {
    ...baseTranslations,
    settings: '设置',
    my_uid: '我的UID',
    language: '语言',
    contact_support: '联系支持',
    legal_info: '法律信息',
    terms_conditions: '条款和条件',
    privacy_policy: '隐私政策',
    acceptable_use: '可接受使用政策',
    copied: '已复制！',
    close: '关闭',
    english: '英语',
    russian: '俄语',
    arabic: '阿拉伯语',
    admin_panel: '管理面板',
    back: '返回',
    home: '主页',
    rank: '排名',
    invite: '邀请',
    mission: '任务',
    admin: '管理',
    balance: '余额',
    withdraw_upper: '提现',
    swap: '兑换',
    weekly_contest: '每周竞赛',
    top_earners: '顶级收入者',
    take_the_prize: '赢得奖品',
    prize_pool: '奖金池',
    income_statistics: '收入统计',
    today: '今天',
    weekly: '每周',
    monthly: '每月',
    all_time: '全部时间',
    streak: '连续',
    days: '天',
    watch_ads: '观看广告',
    earn_pow: '赚取POW',
    daily_limit: '每日限制',
    watch: '观看',
    watching: '观看中...',
    claim: '领取',
    claimed: '已领取',
    viewing_ads: '观看广告',
    get_paid_watching: '在Telegram上观看短广告即可获得报酬。',
    start_earning: '开始赚钱',
    loading_ad: '正在加载广告...',
    verifying: '正在验证...',
    daily_limit_reached_tomorrow: '已达每日限制，明天重置。',
    hourly_limit_reached: '已达每小时限制，约1小时后恢复。',
    ads_available_label: '条广告可用',
    today_label: '今天',
    affiliates: '联盟',
    affiliates_program: '联盟计划',
    we_pay_out: '我们最多支付',
    from_l1_income: '来自1级推荐人的收入，最高',
    from_l2_income: '来自2级推荐人的收入。',
    copy: '复制',
    level1_referrals: '1级推荐',
    of_friends_pow: '来自您朋友的POW',
    from_their_friends: '来自他们的朋友',
    get_label: '获取',
    level2_referrals: '2级推荐',
    bonus: '奖励',
    when_friend_watches: '当您的朋友看1条广告时',
    disabled: '已禁用',
    total_affiliate_earnings: '联盟总收益',
    usd_earned: '已赚取USD',
    total_from_referrals: '所有推荐总计',
    pow_earned: '已赚取POW',
    total_pow_l1: 'L1佣金总POW',
    link_copied: '链接已复制！',
    referral_link: '推荐链接',
    copy_link: '复制链接',
    friends_invited: '已邀请朋友',
    total_earned: '总收益',
    invite_friends: '邀请朋友',
    how_it_works: '如何运作',
    withdraw: '提现',
    withdrawal: '提现',
    amount: '金额',
    wallet_address: '钱包地址',
    submit: '提交',
    minimum: '最低',
    available: '可用',
    history: '历史',
    pending: '待处理',
    completed: '已完成',
    rejected: '已拒绝',
    checking_requirements: '检查要求...',
    pending_withdrawal_warning: '您有待处理的提现请求，请等待处理。',
    select_withdrawal_package: '选择提现套餐',
    full_balance: '全额余额',
    you_will_receive: '您将收到',
    withdrawal_method: '提现方式',
    to_withdraw_need: '提现需要：',
    wallet_activity: '钱包活动',
    no_transactions_yet: '暂无交易',
    withdrawal_history_here: '您的提现历史将显示在这里',
    connect: '连接',
    fee_label: '手续费',
    select_package: '选择套餐',
    insufficient_balance: '余额不足',
    requirements_not_met: '未满足要求',
    withdrawal_request_sent: '提现请求已发送。',
    friends: '位朋友',
    friend: '位朋友',
    ads_count: '个广告',
    ad_count: '条广告',
    ads_watched_progress: '条广告已观看',
    more_ads_to_watch: '还剩',
    full_balance_lower: '全额余额',
    via: '通过',
    enter_withdrawal_amount: '输入提现金额',
    withdraw_balance: '提现余额',
    missions: '任务',
    mission_title: '任务',
    complete_tasks_earn: '完成任务赚取POW奖励',
    promo_code_label: '优惠码',
    earn_with_ads: '通过广告赚钱',
    all_tasks_label: '所有任务',
    all_tab: '全部',
    daily_tab: '每日',
    partner_tab: '合作伙伴',
    no_tasks_available: '暂时没有可用任务',
    come_back_tomorrow: '明天再来',
    no_ad_available: '暂时没有广告，请稍后再试',
    watch_full_ad: '请观看完整广告以赚取收益',
    something_went_wrong: '出了点问题',
    coming_soon_label: '即将推出',
    i_want_task_here: '我想在这里发布任务',
    create_your_own_task: '创建您自己的任务',
    done_label: '完成',
    watch_label: '观看',
    channel_label: '频道',
    bot_website_label: '机器人/网站',
    partner_label: '合作伙伴',
    claim_label: '领取',
    loading_ellipsis: '加载中…',
    share_with_friends: '与朋友分享',
    daily_checkin: '每日签到',
    check_for_updates: '检查更新',
    reward: '奖励',
    go: '前往',
    share: '分享',
    daily_limit_short: '已达每日限制',
    per_day: '/天',
    account_banned_msg: '您的账号因可疑的多账号活动被封禁',
    ban_details: '详情：',
    all_features_disabled: '所有功能已禁用。如果您认为这是错误，请联系我们的',
    support_team: '支持团队',
    admin_self_unban: '解封（管理员）',
    unbanned_successfully: '已成功解封！正在重新加载...',
    not_available: '不可用',
    not_available_country: '此应用在您的国家/地区不可用。',
    join_required: '🔒 需要加入',
    join_required_desc: '要继续使用PaidAdz，您必须加入我们的官方频道和社区群。',
    join_channel: '📢 加入频道',
    join_group: '💬 加入群组',
    verify_membership: '✅ 验证会员资格',
    not_member_yet: '请先加入频道和群组，然后点击验证。',
    loading: '加载中...',
    error: '错误',
    retry: '重试',
    save: '保存',
    cancel: '取消',
    confirm: '确认',
    success: '成功',
    failed: '失败',
    processing: '处理中...',
    select_language: '选择语言',
    language_changed: '语言已更改！',
  },

  pt: {
    ...baseTranslations,
    settings: 'Configurações',
    my_uid: 'Meu UID',
    language: 'Idioma',
    contact_support: 'Contatar Suporte',
    legal_info: 'Informações Legais',
    terms_conditions: 'Termos e Condições',
    privacy_policy: 'Política de Privacidade',
    acceptable_use: 'Política de Uso Aceitável',
    copied: 'Copiado!',
    close: 'Fechar',
    english: 'Inglês',
    russian: 'Russo',
    arabic: 'Árabe',
    admin_panel: 'Painel Admin',
    back: 'Voltar',
    home: 'INÍCIO',
    rank: 'RANKING',
    invite: 'CONVIDAR',
    mission: 'MISSÃO',
    admin: 'ADMIN',
    balance: 'SALDO',
    withdraw_upper: 'SACAR',
    swap: 'TROCAR',
    weekly_contest: 'Concurso Semanal',
    top_earners: 'Maiores Ganhadores',
    take_the_prize: 'levam o prêmio',
    prize_pool: 'Prêmio Total',
    income_statistics: 'ESTATÍSTICAS DE RENDA',
    today: 'Hoje',
    weekly: 'Semanal',
    monthly: 'Mensal',
    all_time: 'Todo o Tempo',
    streak: 'Sequência',
    days: 'dias',
    watch_ads: 'Assistir Anúncios',
    earn_pow: 'Ganhar POW',
    daily_limit: 'Limite Diário',
    watch: 'Assistir',
    watching: 'Assistindo...',
    claim: 'Reivindicar',
    claimed: 'Reivindicado',
    viewing_ads: 'Assistindo Anúncios',
    get_paid_watching: 'Seja pago por assistir anúncios curtos no Telegram.',
    start_earning: 'Começar a Ganhar',
    loading_ad: 'Carregando Anúncio...',
    verifying: 'Verificando...',
    daily_limit_reached_tomorrow: 'Limite diário atingido. Redefine amanhã.',
    hourly_limit_reached: 'Limite horário atingido. Reabastece em ~1 hora.',
    ads_available_label: 'anúncios disponíveis',
    today_label: 'hoje',
    affiliates: 'Afiliados',
    affiliates_program: 'Programa de Afiliados',
    we_pay_out: 'Pagamos até',
    from_l1_income: 'da renda dos indicados do 1º nível e até',
    from_l2_income: 'da renda dos indicados do 2º nível.',
    copy: 'COPIAR',
    level1_referrals: 'Indicados Nível 1',
    of_friends_pow: 'do POW dos seus amigos',
    from_their_friends: 'dos amigos deles',
    get_label: 'Receba',
    level2_referrals: 'Indicados Nível 2',
    bonus: 'Bônus',
    when_friend_watches: 'Quando seu amigo assiste 1 anúncio',
    disabled: 'Desativado',
    total_affiliate_earnings: 'Total de Ganhos de Afiliados',
    usd_earned: 'USD Ganho',
    total_from_referrals: 'Total de todos os indicados',
    pow_earned: 'POW Ganho',
    total_pow_l1: 'Total POW de comissões L1',
    link_copied: 'Link copiado!',
    referral_link: 'Link de Indicação',
    copy_link: 'Copiar Link',
    friends_invited: 'Amigos Convidados',
    total_earned: 'Total Ganho',
    invite_friends: 'Convidar Amigos',
    how_it_works: 'Como Funciona',
    withdraw: 'Sacar',
    withdrawal: 'Saque',
    amount: 'Valor',
    wallet_address: 'Endereço da Carteira',
    submit: 'Enviar',
    minimum: 'Mínimo',
    available: 'Disponível',
    history: 'Histórico',
    pending: 'Pendente',
    completed: 'Concluído',
    rejected: 'Rejeitado',
    checking_requirements: 'Verificando requisitos...',
    pending_withdrawal_warning: 'Você tem um saque pendente. Por favor, aguarde o processamento.',
    select_withdrawal_package: 'Selecionar Pacote de Saque',
    full_balance: 'SALDO TOTAL',
    you_will_receive: 'Você receberá',
    withdrawal_method: 'Método de Saque',
    to_withdraw_need: 'Para sacar você precisa:',
    wallet_activity: 'Atividade da Carteira',
    no_transactions_yet: 'Nenhuma transação ainda',
    withdrawal_history_here: 'Seu histórico de saques aparecerá aqui',
    connect: 'Conectar',
    fee_label: 'taxa',
    select_package: 'Selecionar um Pacote',
    insufficient_balance: 'Saldo Insuficiente',
    requirements_not_met: 'Requisitos Não Atendidos',
    withdrawal_request_sent: 'Solicitação de saque enviada.',
    friends: 'amigos',
    friend: 'amigo',
    ads_count: 'anúncios',
    ad_count: 'anúncio',
    ads_watched_progress: 'anúncios assistidos',
    more_ads_to_watch: 'restantes',
    full_balance_lower: 'Saldo total',
    via: 'via',
    enter_withdrawal_amount: 'Digite o Valor do Saque',
    withdraw_balance: 'Sacar Saldo',
    missions: 'Missões',
    mission_title: 'Missão',
    complete_tasks_earn: 'Complete tarefas e ganhe recompensas POW',
    promo_code_label: 'Código Promo',
    earn_with_ads: 'Ganhe com ANÚNCIOS',
    all_tasks_label: 'Todas as Tarefas',
    all_tab: 'Todos',
    daily_tab: 'Diário',
    partner_tab: 'Parceiro',
    no_tasks_available: 'Sem tarefas disponíveis agora',
    come_back_tomorrow: 'volte amanhã',
    no_ad_available: 'Nenhum anúncio disponível, tente mais tarde',
    watch_full_ad: 'Por favor assista o anúncio completo para ganhar',
    something_went_wrong: 'Algo deu errado',
    coming_soon_label: 'Em Breve',
    i_want_task_here: 'Quero minha tarefa aqui',
    create_your_own_task: 'crie sua própria tarefa',
    done_label: 'FEITO',
    watch_label: 'ASSISTIR',
    channel_label: 'Canal',
    bot_website_label: 'Bot / Site',
    partner_label: 'Parceiro',
    claim_label: 'REIVINDICAR',
    loading_ellipsis: 'Carregando…',
    share_with_friends: 'Compartilhar com Amigos',
    daily_checkin: 'Check-in Diário',
    check_for_updates: 'Verificar Atualizações',
    reward: 'Recompensa',
    go: 'Ir',
    share: 'Compartilhar',
    daily_limit_short: 'Limite diário atingido',
    per_day: '/dia',
    account_banned_msg: 'Sua conta foi banida por atividade suspeita de múltiplas contas',
    ban_details: 'Detalhes:',
    all_features_disabled: 'Todos os recursos estão desativados. Se você acredita que é um erro, entre em contato com nossa',
    support_team: 'equipe de suporte',
    admin_self_unban: 'Desbanir (Admin)',
    unbanned_successfully: 'Desbanido com sucesso! Recarregando...',
    not_available: 'Não Disponível',
    not_available_country: 'Este aplicativo não está disponível em seu país.',
    join_required: '🔒 Participação Necessária',
    join_required_desc: 'Para continuar usando o PaidAdz, você deve participar do nosso Canal oficial e Grupo da Comunidade.',
    join_channel: '📢 Entrar no Canal',
    join_group: '💬 Entrar no Grupo',
    verify_membership: '✅ Verificar Participação',
    not_member_yet: 'Por favor, entre no canal e no grupo primeiro, depois toque em Verificar.',
    loading: 'Carregando...',
    error: 'Erro',
    retry: 'Tentar Novamente',
    save: 'Salvar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    success: 'Sucesso',
    failed: 'Falhou',
    processing: 'Processando...',
    select_language: 'Selecionar Idioma',
    language_changed: 'Idioma alterado!',
  },

  es: {
    ...baseTranslations,
    settings: 'Configuración',
    my_uid: 'Mi UID',
    language: 'Idioma',
    contact_support: 'Contactar Soporte',
    legal_info: 'Información Legal',
    terms_conditions: 'Términos y Condiciones',
    privacy_policy: 'Política de Privacidad',
    acceptable_use: 'Política de Uso Aceptable',
    copied: '¡Copiado!',
    close: 'Cerrar',
    english: 'Inglés',
    russian: 'Ruso',
    arabic: 'Árabe',
    admin_panel: 'Panel de Admin',
    back: 'Volver',
    home: 'INICIO',
    rank: 'RANGO',
    invite: 'INVITAR',
    mission: 'MISIÓN',
    admin: 'ADMIN',
    balance: 'SALDO',
    withdraw_upper: 'RETIRAR',
    swap: 'CAMBIAR',
    weekly_contest: 'Concurso Semanal',
    top_earners: 'Mejores Ganadores',
    take_the_prize: 'ganan el premio',
    prize_pool: 'Bote de Premios',
    income_statistics: 'ESTADÍSTICAS DE INGRESOS',
    today: 'Hoy',
    weekly: 'Semanal',
    monthly: 'Mensual',
    all_time: 'Todo el Tiempo',
    streak: 'Racha',
    days: 'días',
    watch_ads: 'Ver Anuncios',
    earn_pow: 'Ganar POW',
    daily_limit: 'Límite Diario',
    watch: 'Ver',
    watching: 'Viendo...',
    claim: 'Reclamar',
    claimed: 'Reclamado',
    viewing_ads: 'Viendo Anuncios',
    get_paid_watching: 'Gana dinero por ver anuncios cortos en Telegram.',
    start_earning: 'Empezar a Ganar',
    loading_ad: 'Cargando Anuncio...',
    verifying: 'Verificando...',
    daily_limit_reached_tomorrow: 'Límite diario alcanzado. Se restablece mañana.',
    hourly_limit_reached: 'Límite por hora alcanzado. Se restablece en ~1 hora.',
    ads_available_label: 'anuncios disponibles',
    today_label: 'hoy',
    affiliates: 'Afiliados',
    affiliates_program: 'Programa de Afiliados',
    we_pay_out: 'Pagamos hasta',
    from_l1_income: 'de los ingresos de los referidos de nivel 1 y hasta',
    from_l2_income: 'de los ingresos de los referidos de nivel 2.',
    copy: 'COPIAR',
    level1_referrals: 'Referidos Nivel 1',
    of_friends_pow: 'del POW de tus amigos',
    from_their_friends: 'de sus amigos',
    get_label: 'Obtén',
    level2_referrals: 'Referidos Nivel 2',
    bonus: 'Bono',
    when_friend_watches: 'Cuando tu amigo ve 1 anuncio',
    disabled: 'Desactivado',
    total_affiliate_earnings: 'Ganancias Totales de Afiliados',
    usd_earned: 'USD Ganados',
    total_from_referrals: 'Total de todos los referidos',
    pow_earned: 'POW Ganado',
    total_pow_l1: 'Total POW de comisiones L1',
    link_copied: '¡Enlace copiado!',
    referral_link: 'Enlace de Referido',
    copy_link: 'Copiar Enlace',
    friends_invited: 'Amigos Invitados',
    total_earned: 'Total Ganado',
    invite_friends: 'Invitar Amigos',
    how_it_works: 'Cómo Funciona',
    withdraw: 'Retirar',
    withdrawal: 'Retiro',
    amount: 'Cantidad',
    wallet_address: 'Dirección de Billetera',
    submit: 'Enviar',
    minimum: 'Mínimo',
    available: 'Disponible',
    history: 'Historial',
    pending: 'Pendiente',
    completed: 'Completado',
    rejected: 'Rechazado',
    checking_requirements: 'Verificando requisitos...',
    pending_withdrawal_warning: 'Tienes un retiro pendiente. Por favor espera a que sea procesado.',
    select_withdrawal_package: 'Seleccionar Paquete de Retiro',
    full_balance: 'SALDO COMPLETO',
    you_will_receive: 'Recibirás',
    withdrawal_method: 'Método de Retiro',
    to_withdraw_need: 'Para retirar necesitas:',
    wallet_activity: 'Actividad de la Cartera',
    no_transactions_yet: 'Aún no hay transacciones',
    withdrawal_history_here: 'Tu historial de retiros aparecerá aquí',
    connect: 'Conectar',
    fee_label: 'tarifa',
    select_package: 'Seleccionar Paquete',
    insufficient_balance: 'Saldo Insuficiente',
    requirements_not_met: 'Requisitos No Cumplidos',
    withdrawal_request_sent: 'Solicitud de retiro enviada.',
    friends: 'amigos',
    friend: 'amigo',
    ads_count: 'anuncios',
    ad_count: 'anuncio',
    ads_watched_progress: 'anuncios vistos',
    more_ads_to_watch: 'restantes',
    full_balance_lower: 'Saldo completo',
    via: 'vía',
    enter_withdrawal_amount: 'Ingresa el Monto de Retiro',
    withdraw_balance: 'Retirar Saldo',
    missions: 'Misiones',
    mission_title: 'Misión',
    complete_tasks_earn: 'Completa tareas y gana recompensas POW',
    promo_code_label: 'Código Promo',
    earn_with_ads: 'Gana con ANUNCIOS',
    all_tasks_label: 'Todas las Tareas',
    all_tab: 'Todo',
    daily_tab: 'Diario',
    partner_tab: 'Socio',
    no_tasks_available: 'No hay tareas disponibles ahora',
    come_back_tomorrow: 'vuelve mañana',
    no_ad_available: 'No hay anuncios disponibles, intenta más tarde',
    watch_full_ad: 'Por favor ve el anuncio completo para ganar',
    something_went_wrong: 'Algo salió mal',
    coming_soon_label: 'Próximamente',
    i_want_task_here: 'Quiero mi tarea aquí',
    create_your_own_task: 'crea tu propia tarea',
    done_label: 'HECHO',
    watch_label: 'VER',
    channel_label: 'Canal',
    bot_website_label: 'Bot / Sitio web',
    partner_label: 'Socio',
    claim_label: 'RECLAMAR',
    loading_ellipsis: 'Cargando…',
    share_with_friends: 'Compartir con Amigos',
    daily_checkin: 'Registro Diario',
    check_for_updates: 'Buscar Actualizaciones',
    reward: 'Recompensa',
    go: 'Ir',
    share: 'Compartir',
    daily_limit_short: 'Límite diario alcanzado',
    per_day: '/día',
    account_banned_msg: 'Tu cuenta ha sido baneada por actividad sospechosa de múltiples cuentas',
    ban_details: 'Detalles:',
    all_features_disabled: 'Todas las funciones están desactivadas. Si crees que es un error, contacta a nuestro',
    support_team: 'equipo de soporte',
    admin_self_unban: 'Desbanear (Admin)',
    unbanned_successfully: '¡Desbaneado! Recargando...',
    not_available: 'No Disponible',
    not_available_country: 'Esta aplicación no está disponible en tu país.',
    join_required: '🔒 Unión Requerida',
    join_required_desc: 'Para seguir usando PaidAdz, debes unirte a nuestro Canal oficial y Grupo de la Comunidad.',
    join_channel: '📢 Unirse al Canal',
    join_group: '💬 Unirse al Grupo',
    verify_membership: '✅ Verificar Membresía',
    not_member_yet: 'Por favor únete al canal y al grupo primero, luego toca Verificar.',
    loading: 'Cargando...',
    error: 'Error',
    retry: 'Reintentar',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    success: 'Éxito',
    failed: 'Fallido',
    processing: 'Procesando...',
    select_language: 'Seleccionar Idioma',
    language_changed: '¡Idioma cambiado!',
  },

  vi: {
    ...baseTranslations,
    settings: 'Cài đặt',
    my_uid: 'UID của tôi',
    language: 'Ngôn ngữ',
    contact_support: 'Liên hệ hỗ trợ',
    legal_info: 'Thông tin pháp lý',
    terms_conditions: 'Điều khoản & Điều kiện',
    privacy_policy: 'Chính sách bảo mật',
    acceptable_use: 'Chính sách sử dụng hợp lệ',
    copied: 'Đã sao chép!',
    close: 'Đóng',
    english: 'Tiếng Anh',
    russian: 'Tiếng Nga',
    arabic: 'Tiếng Ả Rập',
    admin_panel: 'Bảng quản trị',
    back: 'Quay lại',
    home: 'TRANG CHỦ',
    rank: 'XẾP HẠNG',
    invite: 'MỜI',
    mission: 'NHIỆM VỤ',
    admin: 'ADMIN',
    balance: 'SỐ DƯ',
    withdraw_upper: 'RÚT TIỀN',
    swap: 'ĐỔI',
    weekly_contest: 'Thi Đấu Hàng Tuần',
    top_earners: 'Người Kiếm Nhiều Nhất',
    take_the_prize: 'giành giải thưởng',
    prize_pool: 'Quỹ Giải Thưởng',
    income_statistics: 'THỐNG KÊ THU NHẬP',
    today: 'Hôm nay',
    weekly: 'Hàng tuần',
    monthly: 'Hàng tháng',
    all_time: 'Mọi thời điểm',
    streak: 'Chuỗi',
    days: 'ngày',
    watch_ads: 'Xem quảng cáo',
    earn_pow: 'Kiếm POW',
    daily_limit: 'Giới hạn hằng ngày',
    watch: 'Xem',
    watching: 'Đang xem...',
    claim: 'Nhận',
    claimed: 'Đã nhận',
    viewing_ads: 'Xem quảng cáo',
    get_paid_watching: 'Kiếm tiền khi xem quảng cáo ngắn trên Telegram.',
    start_earning: 'Bắt đầu kiếm tiền',
    loading_ad: 'Đang tải quảng cáo...',
    verifying: 'Đang xác minh...',
    daily_limit_reached_tomorrow: 'Đã đạt giới hạn hàng ngày. Đặt lại vào ngày mai.',
    hourly_limit_reached: 'Đã đạt giới hạn theo giờ. Nạp lại sau ~1 giờ.',
    ads_available_label: 'quảng cáo có sẵn',
    today_label: 'hôm nay',
    affiliates: 'Đối tác',
    affiliates_program: 'Chương trình đối tác',
    we_pay_out: 'Chúng tôi trả đến',
    from_l1_income: 'từ thu nhập của người giới thiệu cấp 1 và đến',
    from_l2_income: 'từ thu nhập của người giới thiệu cấp 2.',
    copy: 'SAO CHÉP',
    level1_referrals: 'Giới thiệu cấp 1',
    of_friends_pow: 'từ POW của bạn bè',
    from_their_friends: 'từ bạn bè của họ',
    get_label: 'Nhận',
    level2_referrals: 'Giới thiệu cấp 2',
    bonus: 'Thưởng',
    when_friend_watches: 'Khi bạn bè xem 1 quảng cáo',
    disabled: 'Đã tắt',
    total_affiliate_earnings: 'Tổng thu nhập đối tác',
    usd_earned: 'USD đã kiếm',
    total_from_referrals: 'Tổng từ tất cả giới thiệu',
    pow_earned: 'POW đã kiếm',
    total_pow_l1: 'Tổng POW từ hoa hồng L1',
    link_copied: 'Đã sao chép liên kết!',
    referral_link: 'Liên kết giới thiệu',
    copy_link: 'Sao chép liên kết',
    friends_invited: 'Bạn bè đã mời',
    total_earned: 'Tổng đã kiếm',
    invite_friends: 'Mời bạn bè',
    how_it_works: 'Cách hoạt động',
    withdraw: 'Rút tiền',
    withdrawal: 'Rút tiền',
    amount: 'Số tiền',
    wallet_address: 'Địa chỉ ví',
    submit: 'Gửi',
    minimum: 'Tối thiểu',
    available: 'Có sẵn',
    history: 'Lịch sử',
    pending: 'Đang chờ',
    completed: 'Hoàn thành',
    rejected: 'Bị từ chối',
    checking_requirements: 'Kiểm tra yêu cầu...',
    pending_withdrawal_warning: 'Bạn có yêu cầu rút tiền đang chờ xử lý. Vui lòng đợi.',
    select_withdrawal_package: 'Chọn gói rút tiền',
    full_balance: 'TOÀN BỘ SỐ DƯ',
    you_will_receive: 'Bạn sẽ nhận được',
    withdrawal_method: 'Phương thức rút tiền',
    to_withdraw_need: 'Để rút tiền cần:',
    wallet_activity: 'Hoạt động ví',
    no_transactions_yet: 'Chưa có giao dịch',
    withdrawal_history_here: 'Lịch sử rút tiền của bạn sẽ hiện ở đây',
    connect: 'Kết nối',
    fee_label: 'phí',
    select_package: 'Chọn gói',
    insufficient_balance: 'Số dư không đủ',
    requirements_not_met: 'Chưa đáp ứng yêu cầu',
    withdrawal_request_sent: 'Đã gửi yêu cầu rút tiền.',
    friends: 'bạn bè',
    friend: 'người bạn',
    ads_count: 'quảng cáo',
    ad_count: 'quảng cáo',
    ads_watched_progress: 'quảng cáo đã xem',
    more_ads_to_watch: 'còn lại',
    full_balance_lower: 'Toàn bộ số dư',
    via: 'qua',
    enter_withdrawal_amount: 'Nhập số tiền rút',
    withdraw_balance: 'Rút số dư',
    missions: 'Nhiệm vụ',
    mission_title: 'Nhiệm vụ',
    complete_tasks_earn: 'Hoàn thành nhiệm vụ để kiếm POW',
    promo_code_label: 'Mã khuyến mãi',
    earn_with_ads: 'Kiếm tiền với QUẢNG CÁO',
    all_tasks_label: 'Tất cả nhiệm vụ',
    all_tab: 'Tất cả',
    daily_tab: 'Hàng ngày',
    partner_tab: 'Đối tác',
    no_tasks_available: 'Không có nhiệm vụ ngay bây giờ',
    come_back_tomorrow: 'quay lại ngày mai',
    no_ad_available: 'Không có quảng cáo ngay bây giờ, thử lại sau',
    watch_full_ad: 'Vui lòng xem đầy đủ quảng cáo để kiếm thưởng',
    something_went_wrong: 'Đã xảy ra lỗi',
    coming_soon_label: 'Sắp ra mắt',
    i_want_task_here: 'Tôi muốn nhiệm vụ của mình ở đây',
    create_your_own_task: 'tạo nhiệm vụ của riêng bạn',
    done_label: 'XONG',
    watch_label: 'XEM',
    channel_label: 'Kênh',
    bot_website_label: 'Bot / Website',
    partner_label: 'Đối tác',
    claim_label: 'NHẬN',
    loading_ellipsis: 'Đang tải…',
    share_with_friends: 'Chia sẻ với bạn bè',
    daily_checkin: 'Điểm danh hàng ngày',
    check_for_updates: 'Kiểm tra cập nhật',
    reward: 'Phần thưởng',
    go: 'Đi',
    share: 'Chia sẻ',
    daily_limit_short: 'Đã đạt giới hạn hằng ngày',
    per_day: '/ngày',
    account_banned_msg: 'Tài khoản của bạn đã bị cấm do hoạt động đáng ngờ với nhiều tài khoản',
    ban_details: 'Chi tiết:',
    all_features_disabled: 'Tất cả tính năng đã bị tắt. Nếu bạn nghĩ đây là lỗi, hãy liên hệ',
    support_team: 'đội hỗ trợ',
    admin_self_unban: 'Bỏ cấm (Admin)',
    unbanned_successfully: 'Đã bỏ cấm! Đang tải lại...',
    not_available: 'Không khả dụng',
    not_available_country: 'Ứng dụng này không khả dụng ở quốc gia của bạn.',
    join_required: '🔒 Yêu cầu tham gia',
    join_required_desc: 'Để tiếp tục sử dụng PaidAdz, bạn phải tham gia Kênh chính thức và Nhóm cộng đồng của chúng tôi.',
    join_channel: '📢 Tham gia Kênh',
    join_group: '💬 Tham gia Nhóm',
    verify_membership: '✅ Xác minh tư cách thành viên',
    not_member_yet: 'Vui lòng tham gia cả kênh và nhóm trước, sau đó nhấn Xác minh.',
    loading: 'Đang tải...',
    error: 'Lỗi',
    retry: 'Thử lại',
    save: 'Lưu',
    cancel: 'Hủy',
    confirm: 'Xác nhận',
    success: 'Thành công',
    failed: 'Thất bại',
    processing: 'Đang xử lý...',
    select_language: 'Chọn ngôn ngữ',
    language_changed: 'Đã thay đổi ngôn ngữ!',
  },

  bn: {
    ...baseTranslations,
    settings: 'সেটিংস',
    my_uid: 'আমার UID',
    language: 'ভাষা',
    contact_support: 'সহায়তায় যোগাযোগ',
    legal_info: 'আইনি তথ্য',
    terms_conditions: 'শর্তাবলী',
    privacy_policy: 'গোপনীয়তা নীতি',
    acceptable_use: 'গ্রহণযোগ্য ব্যবহার নীতি',
    copied: 'কপি হয়েছে!',
    close: 'বন্ধ',
    english: 'ইংরেজি',
    russian: 'রাশিয়ান',
    arabic: 'আরবি',
    admin_panel: 'অ্যাডমিন প্যানেল',
    back: 'ফিরে যান',
    home: 'হোম',
    rank: 'র‍্যাংক',
    invite: 'আমন্ত্রণ',
    mission: 'মিশন',
    admin: 'অ্যাডমিন',
    balance: 'ব্যালেন্স',
    withdraw_upper: 'উত্তোলন',
    swap: 'এক্সচেঞ্জ',
    weekly_contest: 'সাপ্তাহিক প্রতিযোগিতা',
    top_earners: 'শীর্ষ উপার্জনকারী',
    take_the_prize: 'পুরস্কার জিতুন',
    prize_pool: 'পুরস্কার ভান্ডার',
    income_statistics: 'আয়ের পরিসংখ্যান',
    today: 'আজ',
    weekly: 'সাপ্তাহিক',
    monthly: 'মাসিক',
    all_time: 'সর্বকালীন',
    streak: 'ধারা',
    days: 'দিন',
    watch_ads: 'বিজ্ঞাপন দেখুন',
    earn_pow: 'POW উপার্জন করুন',
    daily_limit: 'দৈনিক সীমা',
    watch: 'দেখুন',
    watching: 'দেখছেন...',
    claim: 'দাবি করুন',
    claimed: 'দাবি হয়েছে',
    viewing_ads: 'বিজ্ঞাপন দেখা হচ্ছে',
    get_paid_watching: 'টেলিগ্রামে ছোট বিজ্ঞাপন দেখে অর্থ উপার্জন করুন।',
    start_earning: 'উপার্জন শুরু করুন',
    loading_ad: 'বিজ্ঞাপন লোড হচ্ছে...',
    verifying: 'যাচাই হচ্ছে...',
    daily_limit_reached_tomorrow: 'দৈনিক সীমা পৌঁছে গেছে। কাল রিসেট হবে।',
    hourly_limit_reached: 'ঘণ্টার সীমা পৌঁছে গেছে। ~১ ঘণ্টায় রিফিল হবে।',
    ads_available_label: 'বিজ্ঞাপন পাওয়া যাচ্ছে',
    today_label: 'আজ',
    affiliates: 'অ্যাফিলিয়েট',
    affiliates_program: 'অ্যাফিলিয়েট প্রোগ্রাম',
    we_pay_out: 'আমরা সর্বোচ্চ দিই',
    from_l1_income: '১ম স্তরের রেফারেলদের আয় থেকে এবং সর্বোচ্চ',
    from_l2_income: '২য় স্তরের রেফারেলদের আয় থেকে।',
    copy: 'কপি',
    level1_referrals: '১ম স্তরের রেফারেল',
    of_friends_pow: 'আপনার বন্ধুদের POW থেকে',
    from_their_friends: 'তাদের বন্ধুদের থেকে',
    get_label: 'পান',
    level2_referrals: '২য় স্তরের রেফারেল',
    bonus: 'বোনাস',
    when_friend_watches: 'যখন আপনার বন্ধু ১টি বিজ্ঞাপন দেখেন',
    disabled: 'নিষ্ক্রিয়',
    total_affiliate_earnings: 'মোট অ্যাফিলিয়েট উপার্জন',
    usd_earned: 'USD উপার্জিত',
    total_from_referrals: 'সব রেফারেল থেকে মোট',
    pow_earned: 'POW উপার্জিত',
    total_pow_l1: 'L1 কমিশন থেকে মোট POW',
    link_copied: 'লিংক কপি হয়েছে!',
    referral_link: 'রেফারেল লিংক',
    copy_link: 'লিংক কপি করুন',
    friends_invited: 'আমন্ত্রিত বন্ধু',
    total_earned: 'মোট উপার্জন',
    invite_friends: 'বন্ধু আমন্ত্রণ করুন',
    how_it_works: 'এটি কীভাবে কাজ করে',
    withdraw: 'উত্তোলন',
    withdrawal: 'উত্তোলন',
    amount: 'পরিমাণ',
    wallet_address: 'ওয়ালেট ঠিকানা',
    submit: 'জমা দিন',
    minimum: 'সর্বনিম্ন',
    available: 'উপলব্ধ',
    history: 'ইতিহাস',
    pending: 'অপেক্ষমান',
    completed: 'সম্পন্ন',
    rejected: 'প্রত্যাখ্যাত',
    checking_requirements: 'প্রয়োজনীয়তা যাচাই করা হচ্ছে...',
    pending_withdrawal_warning: 'আপনার একটি অপেক্ষমান উত্তোলন আছে। অনুগ্রহ করে প্রক্রিয়াকরণের জন্য অপেক্ষা করুন।',
    select_withdrawal_package: 'উত্তোলন প্যাকেজ বেছে নিন',
    full_balance: 'সম্পূর্ণ ব্যালেন্স',
    you_will_receive: 'আপনি পাবেন',
    withdrawal_method: 'উত্তোলন পদ্ধতি',
    to_withdraw_need: 'উত্তোলনের জন্য প্রয়োজন:',
    wallet_activity: 'ওয়ালেট কার্যক্রম',
    no_transactions_yet: 'এখনও কোনো লেনদেন নেই',
    withdrawal_history_here: 'আপনার উত্তোলনের ইতিহাস এখানে দেখা যাবে',
    connect: 'সংযুক্ত করুন',
    fee_label: 'ফি',
    select_package: 'একটি প্যাকেজ বেছে নিন',
    insufficient_balance: 'অপর্যাপ্ত ব্যালেন্স',
    requirements_not_met: 'প্রয়োজনীয়তা পূরণ হয়নি',
    withdrawal_request_sent: 'উত্তোলনের অনুরোধ পাঠানো হয়েছে।',
    friends: 'বন্ধু',
    friend: 'বন্ধু',
    ads_count: 'বিজ্ঞাপন',
    ad_count: 'বিজ্ঞাপন',
    ads_watched_progress: 'বিজ্ঞাপন দেখা হয়েছে',
    more_ads_to_watch: 'আরও বাকি',
    full_balance_lower: 'সম্পূর্ণ ব্যালেন্স',
    via: 'মাধ্যমে',
    enter_withdrawal_amount: 'উত্তোলনের পরিমাণ লিখুন',
    withdraw_balance: 'ব্যালেন্স উত্তোলন',
    missions: 'মিশন',
    mission_title: 'মিশন',
    complete_tasks_earn: 'কাজ সম্পন্ন করুন এবং POW পুরস্কার উপার্জন করুন',
    promo_code_label: 'প্রমো কোড',
    earn_with_ads: 'বিজ্ঞাপন দিয়ে উপার্জন করুন',
    all_tasks_label: 'সব কাজ',
    all_tab: 'সব',
    daily_tab: 'দৈনিক',
    partner_tab: 'পার্টনার',
    no_tasks_available: 'এখন কোনো কাজ নেই',
    come_back_tomorrow: 'আগামীকাল ফিরুন',
    no_ad_available: 'এখন কোনো বিজ্ঞাপন নেই, পরে চেষ্টা করুন',
    watch_full_ad: 'উপার্জনের জন্য সম্পূর্ণ বিজ্ঞাপন দেখুন',
    something_went_wrong: 'কিছু একটা ভুল হয়েছে',
    coming_soon_label: 'শীঘ্রই আসছে',
    i_want_task_here: 'আমি এখানে আমার কাজ চাই',
    create_your_own_task: 'নিজের কাজ তৈরি করুন',
    done_label: 'সম্পন্ন',
    watch_label: 'দেখুন',
    channel_label: 'চ্যানেল',
    bot_website_label: 'বট / ওয়েবসাইট',
    partner_label: 'পার্টনার',
    claim_label: 'দাবি করুন',
    loading_ellipsis: 'লোড হচ্ছে…',
    share_with_friends: 'বন্ধুদের সাথে শেয়ার করুন',
    daily_checkin: 'দৈনিক চেক-ইন',
    check_for_updates: 'আপডেট যাচাই করুন',
    reward: 'পুরস্কার',
    go: 'যান',
    share: 'শেয়ার',
    daily_limit_short: 'দৈনিক সীমা পৌঁছে গেছে',
    per_day: '/দিন',
    account_banned_msg: 'একাধিক অ্যাকাউন্টের সন্দেহজনক কার্যকলাপের কারণে আপনার অ্যাকাউন্ট নিষিদ্ধ করা হয়েছে',
    ban_details: 'বিবরণ:',
    all_features_disabled: 'সমস্ত বৈশিষ্ট্য অক্ষম করা হয়েছে। যদি আপনি মনে করেন এটি একটি ভুল, আমাদের সাথে যোগাযোগ করুন',
    support_team: 'সহায়তা দল',
    admin_self_unban: 'আনব্যান (অ্যাডমিন)',
    unbanned_successfully: 'সফলভাবে আনব্যান হয়েছে! পুনরায় লোড হচ্ছে...',
    not_available: 'পাওয়া যাচ্ছে না',
    not_available_country: 'এই অ্যাপটি আপনার দেশে পাওয়া যায় না।',
    join_required: '🔒 যোগ দিতে হবে',
    join_required_desc: 'PaidAdz ব্যবহার চালিয়ে যেতে, আপনাকে আমাদের অফিসিয়াল চ্যানেল ও কমিউনিটি গ্রুপে যোগ দিতে হবে।',
    join_channel: '📢 চ্যানেলে যোগ দিন',
    join_group: '💬 গ্রুপে যোগ দিন',
    verify_membership: '✅ সদস্যপদ যাচাই করুন',
    not_member_yet: 'প্রথমে চ্যানেল ও গ্রুপে যোগ দিন, তারপর যাচাই করুন।',
    loading: 'লোড হচ্ছে...',
    error: 'ত্রুটি',
    retry: 'পুনরায় চেষ্টা করুন',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    confirm: 'নিশ্চিত করুন',
    success: 'সফল',
    failed: 'ব্যর্থ',
    processing: 'প্রক্রিয়াকরণ...',
    select_language: 'ভাষা নির্বাচন করুন',
    language_changed: 'ভাষা পরিবর্তন হয়েছে!',
  },
};

export function getTranslation(key: string): string {
  try {
    const saved = localStorage.getItem('app_language') as Language;
    const lang = saved && Object.keys(translations).includes(saved) ? saved : 'en';
    return translations[lang]?.[key] ?? translations['en']?.[key] ?? key;
  } catch {
    return translations['en']?.[key] ?? key;
  }
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
  isRTL: false,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('app_language') as Language;
      if (saved && Object.keys(translations).includes(saved)) {
        setLanguageState(saved);
      }
    } catch {}
  }, []);

  // Apply RTL direction to <html> tag whenever language changes
  useEffect(() => {
    const isRTL = language === 'ar';
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('app_language', lang);
    } catch {}
  };

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations['en']?.[key] ?? key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
