import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ru' | 'ar' | 'uk' | 'de' | 'zh' | 'pt' | 'es' | 'vi' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const baseTranslations: Record<string, string> = {
  settings: 'Settings',
  my_uid: 'My UID',
  language: 'Language',
  contact_support: 'Contact Support',
  legal_info: 'Legal Information',
  terms_conditions: 'Terms & Conditions',
  privacy_policy: 'Privacy Policy',
  acceptable_use: 'Acceptable Use Policy',
  copied: 'Copied to clipboard!',
  close: 'Close',
  english: 'English',
  russian: 'Russian',
  arabic: 'Arabic',
  admin_panel: 'Admin Panel',
  back: 'Back',
  home: 'HOME',
  rank: 'RANK',
  invite: 'INVITE',
  mission: 'MISSION',
  admin: 'ADMIN',
  balance: 'BALANCE',
  withdraw_upper: 'WITHDRAW',
  swap: 'SWAP',
  income_statistics: 'INCOME STATISTICS',
  today: 'Today',
  weekly: 'Weekly',
  monthly: 'Monthly',
  all_time: 'All-Time',
  streak: 'Streak',
  days: 'days',
  watch_ads: 'Watch Ads',
  earn_pow: 'Earn POW',
  daily_limit: 'Daily Limit',
  watch: 'Watch',
  watching: 'Watching...',
  claim: 'Claim',
  claimed: 'Claimed',
  viewing_ads: 'Viewing Ads',
  get_paid_watching: 'Get paid for watching short Ads on Telegram.',
  start_earning: 'Start Earning',
  loading_ad: 'Loading Ad...',
  verifying: 'Verifying...',
  daily_limit_reached_tomorrow: 'Daily limit reached. Resets tomorrow.',
  hourly_limit_reached: 'Hourly limit reached. Refills in ~1 hour.',
  ads_available_label: 'ads available',
  today_label: 'today',
  affiliates: 'Affiliates',
  affiliates_program: 'Affiliates Program',
  we_pay_out: 'We pay out up to',
  from_l1_income: 'from the income of referrals of the 1st level and up to',
  from_l2_income: 'from the income of referrals of the 2nd level.',
  copy: 'COPY',
  level1_referrals: 'Level 1 Referrals',
  of_friends_pow: 'of your friends POW',
  from_their_friends: 'from their friends',
  get_label: 'Get',
  level2_referrals: 'Level 2 Referrals',
  bonus: 'Bonus',
  when_friend_watches: 'When your friend watches 1 ad',
  disabled: 'Disabled',
  total_affiliate_earnings: 'Total Affiliate Earnings',
  usd_earned: 'USD Earned',
  total_from_referrals: 'Total from all referrals',
  pow_earned: 'POW Earned',
  total_pow_l1: 'Total POW from L1 commissions',
  link_copied: 'Link copied!',
  referral_link: 'Referral Link',
  copy_link: 'Copy Link',
  friends_invited: 'Friends Invited',
  total_earned: 'Total Earned',
  invite_friends: 'Invite Friends',
  how_it_works: 'How It Works',
  withdraw: 'Withdraw',
  withdrawal: 'Withdrawal',
  amount: 'Amount',
  wallet_address: 'Wallet Address',
  submit: 'Submit',
  minimum: 'Minimum',
  available: 'Available',
  history: 'History',
  pending: 'Pending',
  completed: 'Completed',
  rejected: 'Rejected',
  checking_requirements: 'Checking requirements...',
  pending_withdrawal_warning: 'You have a pending withdrawal. Please wait for it to be processed.',
  select_withdrawal_package: 'Select Withdrawal Package',
  full_balance: 'FULL BALANCE',
  you_will_receive: 'You will receive',
  withdrawal_method: 'Withdrawal method',
  to_withdraw_need: 'To withdraw you need:',
  wallet_activity: 'Wallet Activity',
  no_transactions_yet: 'No transactions yet',
  withdrawal_history_here: 'Your withdrawal history will appear here',
  connect: 'Connect',
  fee_label: 'fee',
  select_package: 'Select a Package',
  insufficient_balance: 'Insufficient Balance',
  requirements_not_met: 'Requirements Not Met',
  withdrawal_request_sent: 'You have sent a withdrawal request.',
  friends: 'friends',
  friend: 'friend',
  ads_count: 'ads',
  ad_count: 'ad',
  ads_watched_progress: 'ads watched',
  more_ads_to_watch: 'more to go',
  full_balance_lower: 'Full balance',
  via: 'via',
  enter_withdrawal_amount: 'Enter Withdrawal Amount',
  withdraw_balance: 'Withdraw Balance',
  missions: 'Missions',
  mission_title: 'Mission',
  complete_tasks_earn: 'Complete tasks and earn POW rewards',
  promo_code_label: 'Promo Code',
  earn_with_ads: 'Earn with ADS',
  all_tasks_label: 'All Tasks',
  all_tab: 'All',
  daily_tab: 'Daily',
  partner_tab: 'Partner',
  no_tasks_available: 'No tasks available right now',
  come_back_tomorrow: 'come back tomorrow',
  no_ad_available: 'No ad available right now, try again later',
  watch_full_ad: 'Please watch the full ad to earn',
  something_went_wrong: 'Something went wrong',
  coming_soon_label: 'Coming Soon',
  i_want_task_here: 'I want my task here',
  create_your_own_task: 'create your own task',
  done_label: 'DONE',
  watch_label: 'WATCH',
  channel_label: 'Channel',
  bot_website_label: 'Bot / Website',
  partner_label: 'Partner',
  claim_label: 'CLAIM',
  loading_ellipsis: 'Loading…',
  share_with_friends: 'Share with Friends',
  daily_checkin: 'Daily Check-in',
  check_for_updates: 'Check for Updates',
  reward: 'Reward',
  go: 'Go',
  share: 'Share',
  daily_limit_short: 'Daily limit reached',
  per_day: '/day',
  account_banned_msg: 'Your account has been banned due to suspicious multi-account activity',
  ban_details: 'Details:',
  all_features_disabled: 'All features are disabled. If you believe this is a mistake, please contact our',
  support_team: 'support team',
  admin_self_unban: 'Admin Self-Unban',
  unbanned_successfully: 'Successfully unbanned! Reloading...',
  not_available: 'Not Available',
  not_available_country: 'This app is not available in your country.',
  join_required: '🔒 Join Required',
  join_required_desc: 'To continue using PaidAdz, you must join our official Channel and Community Group.',
  join_channel: '📢 Join Channel',
  join_group: '💬 Join Group',
  verify_membership: '✅ Verify Membership',
  not_member_yet: 'Please join both the channel and group first, then tap Verify.',
  loading: 'Loading...',
  error: 'Error',
  retry: 'Retry',
  save: 'Save',
  cancel: 'Cancel',
  confirm: 'Confirm',
  success: 'Success',
  failed: 'Failed',
  processing: 'Processing...',
  select_language: 'Select Language',
  language_changed: 'Language changed!',
};

const translations: Record<Language, Record<string, string>> = {
  en: baseTranslations,

  ru: {
    ...baseTranslations,
    settings: 'Настройки',
    my_uid: 'Мой UID',
    language: 'Язык',
    contact_support: 'Поддержка',
    legal_info: 'Юридическая информация',
    terms_conditions: 'Условия и положения',
    privacy_policy: 'Политика конфиденциальности',
    acceptable_use: 'Правила использования',
    copied: 'Скопировано!',
    close: 'Закрыть',
    english: 'Английский',
    russian: 'Русский',
    arabic: 'Арабский',
    admin_panel: 'Панель администратора',
    back: 'Назад',
    home: 'ГЛАВНАЯ',
    rank: 'РЕЙТИНГ',
    invite: 'ПРИГЛАСИТЬ',
    mission: 'ЗАДАНИЯ',
    admin: 'ADMIN',
    balance: 'БАЛАНС',
    withdraw_upper: 'ВЫВОД',
    swap: 'ОБМЕН',
    income_statistics: 'СТАТИСТИКА ДОХОДА',
    today: 'Сегодня',
    weekly: 'За неделю',
    monthly: 'За месяц',
    all_time: 'За всё время',
    streak: 'Серия',
    days: 'дней',
    watch_ads: 'Смотреть рекламу',
    earn_pow: 'Заработать POW',
    daily_limit: 'Дневной лимит',
    watch: 'Смотреть',
    watching: 'Просмотр...',
    claim: 'Получить',
    claimed: 'Получено',
    viewing_ads: 'Просмотр рекламы',
    get_paid_watching: 'Получайте деньги за просмотр коротких реклам в Telegram.',
    start_earning: 'Начать зарабатывать',
    loading_ad: 'Загрузка рекламы...',
    verifying: 'Проверяем...',
    daily_limit_reached_tomorrow: 'Дневной лимит исчерпан. Сбросится завтра.',
    hourly_limit_reached: 'Часовой лимит исчерпан. Обновится через ~1 час.',
    ads_available_label: 'реклам доступно',
    today_label: 'сегодня',
    affiliates: 'Партнёры',
    affiliates_program: 'Партнёрская программа',
    we_pay_out: 'Мы выплачиваем до',
    from_l1_income: 'от дохода рефералов 1-го уровня и до',
    from_l2_income: 'от дохода рефералов 2-го уровня.',
    copy: 'КОПИРОВАТЬ',
    level1_referrals: 'Рефералы 1-го уровня',
    of_friends_pow: 'от POW ваших друзей',
    from_their_friends: 'от доходов их друзей',
    get_label: 'Получайте',
    level2_referrals: 'Рефералы 2-го уровня',
    bonus: 'Бонус',
    when_friend_watches: 'Когда ваш друг посмотрит 1 рекламу',
    disabled: 'Отключено',
    total_affiliate_earnings: 'Всего заработано с партнёров',
    usd_earned: 'Заработано USD',
    total_from_referrals: 'Итого от всех рефералов',
    pow_earned: 'Заработано POW',
    total_pow_l1: 'Всего POW от комиссий L1',
    link_copied: 'Ссылка скопирована!',
    referral_link: 'Реферальная ссылка',
    copy_link: 'Копировать ссылку',
    friends_invited: 'Приглашено друзей',
    total_earned: 'Всего заработано',
    invite_friends: 'Пригласить друзей',
    how_it_works: 'Как это работает',
    withdraw: 'Вывод',
    withdrawal: 'Вывод средств',
    amount: 'Сумма',
    wallet_address: 'Адрес кошелька',
    submit: 'Отправить',
    minimum: 'Минимум',
    available: 'Доступно',
    history: 'История',
    pending: 'В обработке',
    completed: 'Завершено',
    rejected: 'Отклонено',
    checking_requirements: 'Проверка условий...',
    pending_withdrawal_warning: 'У вас есть незавершённый вывод. Пожалуйста, дождитесь его обработки.',
    select_withdrawal_package: 'Выберите сумму вывода',
    full_balance: 'ВЕСЬ БАЛАНС',
    you_will_receive: 'Вы получите',
    withdrawal_method: 'Способ вывода',
    to_withdraw_need: 'Для вывода необходимо:',
    wallet_activity: 'Активность кошелька',
    no_transactions_yet: 'Транзакций пока нет',
    withdrawal_history_here: 'История ваших выводов появится здесь',
    connect: 'Подключить',
    fee_label: 'комиссия',
    select_package: 'Выберите пакет',
    insufficient_balance: 'Недостаточно средств',
    requirements_not_met: 'Условия не выполнены',
    withdrawal_request_sent: 'Запрос на вывод отправлен.',
    friends: 'друзей',
    friend: 'друга',
    ads_count: 'реклам',
    ad_count: 'реклам',
    ads_watched_progress: 'реклам просмотрено',
    more_ads_to_watch: 'осталось',
    full_balance_lower: 'Весь баланс',
    via: 'через',
    enter_withdrawal_amount: 'Введите сумму вывода',
    withdraw_balance: 'Вывод баланса',
    missions: 'Задания',
    mission_title: 'Задания',
    complete_tasks_earn: 'Выполняйте задания и зарабатывайте POW',
    promo_code_label: 'Промокод',
    earn_with_ads: 'Заработок с РЕКЛАМОЙ',
    all_tasks_label: 'Все задания',
    all_tab: 'Все',
    daily_tab: 'Ежедневные',
    partner_tab: 'Партнёры',
    no_tasks_available: 'Сейчас нет доступных заданий',
    come_back_tomorrow: 'возвращайтесь завтра',
    no_ad_available: 'Реклама недоступна, попробуйте позже',
    watch_full_ad: 'Пожалуйста, досмотрите рекламу до конца',
    something_went_wrong: 'Что-то пошло не так',
    coming_soon_label: 'Скоро',
    i_want_task_here: 'Хочу разместить задание здесь',
    create_your_own_task: 'создайте своё задание',
    done_label: 'ГОТОВО',
    watch_label: 'СМОТРЕТЬ',
    channel_label: 'Канал',
    bot_website_label: 'Бот / Сайт',
    partner_label: 'Партнёр',
    claim_label: 'ПОЛУЧИТЬ',
    loading_ellipsis: 'Загрузка…',
    share_with_friends: 'Поделиться с друзьями',
    daily_checkin: 'Ежедневный вход',
    check_for_updates: 'Проверить обновления',
    reward: 'Награда',
    go: 'Перейти',
    share: 'Поделиться',
    daily_limit_short: 'Дневной лимит исчерпан',
    per_day: '/день',
    account_banned_msg: 'Ваш аккаунт заблокирован из-за подозрительной активности с несколькими аккаунтами',
    ban_details: 'Подробности:',
    all_features_disabled: 'Все функции отключены. Если вы считаете, что это ошибка, свяжитесь с нашей',
    support_team: 'службой поддержки',
    admin_self_unban: 'Разблокировать (Админ)',
    unbanned_successfully: 'Разблокировано! Перезагрузка...',
    not_available: 'Недоступно',
    not_available_country: 'Это приложение недоступно в вашей стране.',
    join_required: '🔒 Требуется вступление',
    join_required_desc: 'Чтобы продолжить использование PaidAdz, вы должны вступить в наш официальный канал и группу сообщества.',
    join_channel: '📢 Вступить в канал',
    join_group: '💬 Вступить в группу',
    verify_membership: '✅ Подтвердить членство',
    not_member_yet: 'Сначала вступите в канал и группу, затем нажмите «Подтвердить».',
    loading: 'Загрузка...',
    error: 'Ошибка',
    retry: 'Повторить',
    save: 'Сохранить',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    success: 'Успешно',
    failed: 'Не удалось',
    processing: 'Обработка...',
    select_language: 'Выберите язык',
    language_changed: 'Язык изменён!',
  },

  ar: {
    ...baseTranslations,
    settings: 'الإعدادات',
    my_uid: 'معرّفي',
    language: 'اللغة',
    contact_support: 'التواصل مع الدعم',
    legal_info: 'المعلومات القانونية',
    terms_conditions: 'الشروط والأحكام',
    privacy_policy: 'سياسة الخصوصية',
    acceptable_use: 'سياسة الاستخدام المقبول',
    copied: 'تم النسخ!',
    close: 'إغلاق',
    english: 'الإنجليزية',
    russian: 'الروسية',
    arabic: 'العربية',
    admin_panel: 'لوحة الإدارة',
    back: 'رجوع',
    home: 'الرئيسية',
    rank: 'الترتيب',
    invite: 'دعوة',
    mission: 'المهام',
    admin: 'مدير',
    balance: 'الرصيد',
    withdraw_upper: 'سحب',
    swap: 'تحويل',
    weekly_contest: 'مسابقة الأسبوع',
    top_earners: 'أعلى المكتسبين',
    take_the_prize: 'يفوزون بالجائزة',
    prize_pool: 'مجموع الجوائز',
    income_statistics: 'إحصائيات الدخل',
    today: 'اليوم',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    all_time: 'كل الوقت',
    streak: 'التسلسل',
    days: 'أيام',
    leaderboard: 'لوحة المتصدرين',
    weekly_prize: 'الجائزة الأسبوعية',
    watch_ads: 'مشاهدة الإعلانات',
    earn_pow: 'اكسب POW',
    daily_limit: 'الحد اليومي',
    watch: 'شاهد',
    watching: 'جارٍ المشاهدة...',
    claim: 'استلام',
    claimed: 'تم الاستلام',
    viewing_ads: 'مشاهدة الإعلانات',
    get_paid_watching: 'احصل على أموال مقابل مشاهدة إعلانات قصيرة على تيليغرام.',
    start_earning: 'ابدأ الكسب',
    loading_ad: 'جارٍ تحميل الإعلان...',
    verifying: 'جارٍ التحقق...',
    daily_limit_reached_tomorrow: 'تم بلوغ الحد اليومي. يُعاد ضبطه غداً.',
    hourly_limit_reached: 'تم بلوغ الحد الساعي. يتجدد خلال ساعة.',
    ads_available_label: 'إعلانات متاحة',
    today_label: 'اليوم',
    affiliates: 'الشركاء',
    affiliates_program: 'برنامج الشراكة',
    we_pay_out: 'ندفع حتى',
    from_l1_income: 'من دخل الإحالات من المستوى الأول وحتى',
    from_l2_income: 'من دخل الإحالات من المستوى الثاني.',
    copy: 'نسخ',
    level1_referrals: 'إحالات المستوى الأول',
    of_friends_pow: 'من POW أصدقائك',
    from_their_friends: 'من أصدقائهم',
    get_label: 'احصل على',
    level2_referrals: 'إحالات المستوى الثاني',
    bonus: 'مكافأة',
    when_friend_watches: 'عندما يشاهد صديقك إعلاناً واحداً',
    disabled: 'معطّل',
    total_affiliate_earnings: 'إجمالي أرباح الشراكة',
    usd_earned: 'USD مكتسب',
    total_from_referrals: 'الإجمالي من جميع الإحالات',
    pow_earned: 'POW مكتسب',
    total_pow_l1: 'إجمالي POW من عمولات L1',
    link_copied: 'تم نسخ الرابط!',
    referral_link: 'رابط الإحالة',
    copy_link: 'نسخ الرابط',
    friends_invited: 'الأصدقاء المدعوون',
    total_earned: 'إجمالي المكتسب',
    invite_friends: 'دعوة الأصدقاء',
    how_it_works: 'كيف يعمل',
    withdraw: 'سحب',
    withdrawal: 'السحب',
    amount: 'المبلغ',
    wallet_address: 'عنوان المحفظة',
    submit: 'إرسال',
    minimum: 'الحد الأدنى',
    available: 'متاح',
    history: 'السجل',
    pending: 'قيد الانتظار',
    completed: 'مكتمل',
    rejected: 'مرفوض',
    checking_requirements: 'جارٍ التحقق من المتطلبات...',
    pending_withdrawal_warning: 'لديك سحب معلق. يرجى الانتظار حتى تتم معالجته.',
    select_withdrawal_package: 'اختر حزمة السحب',
    full_balance: 'الرصيد الكامل',
    you_will_receive: 'ستستلم',
    withdrawal_method: 'طريقة السحب',
    to_withdraw_need: 'للسحب تحتاج:',
    wallet_activity: 'نشاط المحفظة',
    no_transactions_yet: 'لا توجد معاملات بعد',
    withdrawal_history_here: 'سيظهر سجل سحوباتك هنا',
    connect: 'اتصال',
    fee_label: 'رسوم',
    select_package: 'اختر حزمة',
    insufficient_balance: 'رصيد غير كافٍ',
    requirements_not_met: 'المتطلبات غير مستوفاة',
    withdrawal_request_sent: 'تم إرسال طلب السحب.',
    friends: 'أصدقاء',
    friend: 'صديق',
    ads_count: 'إعلانات',
    ad_count: 'إعلان',
    ads_watched_progress: 'إعلانات تمت مشاهدتها',
    more_ads_to_watch: 'متبقية',
    full_balance_lower: 'الرصيد الكامل',
    via: 'عبر',
    enter_withdrawal_amount: 'أدخل مبلغ السحب',
    withdraw_balance: 'سحب الرصيد',
    this_week: '⭐ هذا الأسبوع',
    last_week: '🗓 الأسبوع الماضي',
    contest_ends_in: 'تنتهي المسابقة في',
    last_week_final: '🏁 النتائج النهائية للأسبوع الماضي',
    weekly_prize_pool: 'مجموع جوائز الأسبوع',
    last_week_prize: 'جائزة الأسبوع الماضي',
    top_10_winners: 'أفضل 10 فائزين',
    earn_stars_by: 'اكسب نجوماً بمشاهدة الإعلانات',
    no_data_last_week: 'لا توجد بيانات للأسبوع الماضي',
    no_participants_yet: 'لا يوجد مشاركون بعد',
    last_week_no_data: 'لم تكن هناك بيانات للأسبوع الماضي.',
    watch_to_top_spot: 'شاهد الإعلانات لكسب النجوم والمطالبة بالمركز الأول!',
    top_10_players: 'أفضل 10 لاعبين',
    you_label: 'أنت',
    your_rank: 'ترتيبك',
    keep_watching_climb: 'استمر في المشاهدة للارتقاء!',
    this_week_label: 'هذا الأسبوع',
    not_ranked_yet: 'لم تُصنَّف بعد هذا الأسبوع',
    watch_to_enter: 'شاهد الإعلانات لكسب النجوم والدخول في المسابقة',
    you_are_winning: 'أنت تفوز',
    missions: 'المهام',
    mission_title: 'المهام',
    complete_tasks_earn: 'أكمل المهام واكسب مكافآت POW',
    promo_code_label: 'رمز ترويجي',
    earn_with_ads: 'اكسب مع الإعلانات',
    all_tasks_label: 'جميع المهام',
    all_tab: 'الكل',
    daily_tab: 'يومي',
    partner_tab: 'الشركاء',
    no_tasks_available: 'لا توجد مهام متاحة الآن',
    come_back_tomorrow: 'عُد غداً',
    no_ad_available: 'لا يوجد إعلان متاح الآن، حاول لاحقاً',
    watch_full_ad: 'يرجى مشاهدة الإعلان كاملاً للكسب',
    something_went_wrong: 'حدث خطأ ما',
    coming_soon_label: 'قريباً',
    i_want_task_here: 'أريد مهمتي هنا',
    create_your_own_task: 'أنشئ مهمتك الخاصة',
    done_label: 'تم',
    watch_label: 'شاهد',
    channel_label: 'قناة',
    bot_website_label: 'بوت / موقع',
    partner_label: 'شريك',
    claim_label: 'استلام',
    loading_ellipsis: 'جارٍ التحميل…',
    share_with_friends: 'شارك مع الأصدقاء',
    daily_checkin: 'تسجيل الدخول اليومي',
    check_for_updates: 'التحقق من التحديثات',
    reward: 'مكافأة',
    go: 'انتقل',
    share: 'شارك',
    daily_limit_short: 'تم بلوغ الحد اليومي',
    per_day: '/يوم',
    account_banned_msg: 'تم حظر حسابك بسبب نشاط مشبوه بحسابات متعددة',
    ban_details: 'التفاصيل:',
    all_features_disabled: 'جميع الميزات معطّلة. إذا كنت تعتقد أن هذا خطأ، يرجى التواصل مع',
    support_team: 'فريق الدعم',
    admin_self_unban: 'إلغاء الحظر (المشرف)',
    unbanned_successfully: 'تم إلغاء الحظر! جارٍ إعادة التحميل...',
    not_available: 'غير متاح',
    not_available_country: 'هذا التطبيق غير متاح في بلدك.',
    join_required: '🔒 الانضمام مطلوب',
    join_required_desc: 'لمواصلة استخدام PaidAdz، يجب عليك الانضمام إلى قناتنا الرسمية ومجموعة المجتمع.',
    join_channel: '📢 انضم إلى القناة',
    join_group: '💬 انضم إلى المجموعة',
    verify_membership: '✅ تحقق من العضوية',
    not_member_yet: 'يرجى الانضمام إلى القناة والمجموعة أولاً، ثم اضغط تحقق.',
    loading: 'جارٍ التحميل...',
    error: 'خطأ',
    retry: 'إعادة المحاولة',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    success: 'نجاح',
    failed: 'فشل',
    processing: 'جارٍ المعالجة...',
    select_language: 'اختر اللغة',
    language_changed: 'تم تغيير اللغة!',
  },

  uk: {
    ...baseTranslations,
    settings: 'Налаштування',
    language: 'Мова',
    copied: 'Скопійовано!',
    close: 'Закрити',
    back: 'Назад',
    home: 'ГОЛОВНА',
    rank: 'РЕЙТИНГ',
    invite: 'ЗАПРОСИТИ',
    mission: 'ЗАВДАННЯ',
    balance: 'БАЛАНС',
    withdraw_upper: 'ВИВЕДЕННЯ',
    weekly_contest: 'ТИЖНЕВИЙ КОНКУРС',
    top_earners: 'Топ учасники',
    take_the_prize: 'беруть приз',
    prize_pool: 'ПРИЗОВИЙ ФОНД',
    today: 'Сьогодні',
    weekly: 'За тиждень',
    monthly: 'За місяць',
    all_time: 'За весь час',
    streak: 'Серія',
    days: 'днів',
    watch_ads: 'Дивитись рекламу',
    earn_pow: 'Заробити POW',
    daily_limit: 'Денний ліміт',
    watch: 'Дивитись',
    watching: 'Перегляд...',
    claim: 'Отримати',
    claimed: 'Отримано',
    viewing_ads: 'Перегляд реклами',
    get_paid_watching: 'Отримуйте гроші за перегляд коротких реклам у Telegram.',
    start_earning: 'Почати заробляти',
    withdraw: 'Виведення',
    withdrawal: 'Виведення коштів',
    amount: 'Сума',
    submit: 'Надіслати',
    minimum: 'Мінімум',
    available: 'Доступно',
    history: 'Історія',
    pending: 'В обробці',
    completed: 'Завершено',
    rejected: 'Відхилено',
    checking_requirements: 'Перевірка умов...',
    pending_withdrawal_warning: 'У вас є незавершений вивід. Будь ласка, дочекайтесь його обробки.',
    you_will_receive: 'Ви отримаєте',
    withdrawal_method: 'Спосіб виведення',
    wallet_activity: 'Активність гаманця',
    no_transactions_yet: 'Транзакцій поки немає',
    withdrawal_history_here: 'Ваша історія виведень з\'явиться тут',
    connect: 'Підключити',
    insufficient_balance: 'Недостатньо коштів',
    requirements_not_met: 'Умови не виконано',
    withdrawal_request_sent: 'Запит на виведення надіслано.',
    friends: 'друзів',
    friend: 'друга',
    ads_count: 'реклам',
    enter_withdrawal_amount: 'Введіть суму виведення',
    withdraw_balance: 'Виведення балансу',
    missions: 'Завдання',
    loading: 'Завантаження...',
    error: 'Помилка',
    retry: 'Повторити',
    save: 'Зберегти',
    cancel: 'Скасувати',
    confirm: 'Підтвердити',
    success: 'Успішно',
    failed: 'Не вдалося',
    processing: 'Обробка...',
    select_language: 'Виберіть мову',
    language_changed: 'Мову змінено!',
  },

  de: {
    ...baseTranslations,
    settings: 'Einstellungen',
    language: 'Sprache',
    copied: 'Kopiert!',
    close: 'Schließen',
    back: 'Zurück',
    home: 'START',
    rank: 'RANG',
    invite: 'EINLADEN',
    mission: 'MISSION',
    balance: 'GUTHABEN',
    withdraw_upper: 'ABHEBEN',
    weekly_contest: 'WÖCHENTLICHER WETTBEWERB',
    top_earners: 'Top-Verdiener',
    take_the_prize: 'gewinnen den Preis',
    prize_pool: 'PREISPOOL',
    today: 'Heute',
    weekly: 'Wöchentlich',
    monthly: 'Monatlich',
    all_time: 'Gesamt',
    streak: 'Serie',
    days: 'Tage',
    watch_ads: 'Werbung ansehen',
    earn_pow: 'POW verdienen',
    daily_limit: 'Tageslimit',
    watch: 'Ansehen',
    watching: 'Schaue...',
    claim: 'Einfordern',
    claimed: 'Eingefordert',
    viewing_ads: 'Werbung ansehen',
    get_paid_watching: 'Werde bezahlt fürs Anschauen von kurzen Anzeigen auf Telegram.',
    start_earning: 'Jetzt verdienen',
    withdraw: 'Abheben',
    withdrawal: 'Auszahlung',
    amount: 'Betrag',
    submit: 'Einreichen',
    minimum: 'Minimum',
    available: 'Verfügbar',
    history: 'Verlauf',
    pending: 'Ausstehend',
    completed: 'Abgeschlossen',
    rejected: 'Abgelehnt',
    checking_requirements: 'Anforderungen prüfen...',
    pending_withdrawal_warning: 'Du hast eine ausstehende Auszahlung. Bitte warte auf die Bearbeitung.',
    you_will_receive: 'Du erhältst',
    withdrawal_method: 'Auszahlungsmethode',
    wallet_activity: 'Wallet-Aktivität',
    no_transactions_yet: 'Noch keine Transaktionen',
    withdrawal_history_here: 'Deine Auszahlungshistorie erscheint hier',
    connect: 'Verbinden',
    insufficient_balance: 'Unzureichendes Guthaben',
    requirements_not_met: 'Anforderungen nicht erfüllt',
    withdrawal_request_sent: 'Auszahlungsanfrage gesendet.',
    friends: 'Freunde',
    friend: 'Freund',
    ads_count: 'Anzeigen',
    enter_withdrawal_amount: 'Auszahlungsbetrag eingeben',
    withdraw_balance: 'Guthaben abheben',
    missions: 'Missionen',
    loading: 'Laden...',
    error: 'Fehler',
    retry: 'Wiederholen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    success: 'Erfolg',
    failed: 'Fehlgeschlagen',
    processing: 'Verarbeitung...',
    select_language: 'Sprache auswählen',
    language_changed: 'Sprache geändert!',
  },

  zh: {
    ...baseTranslations,
    settings: '设置',
    language: '语言',
    copied: '已复制！',
    close: '关闭',
    back: '返回',
    home: '主页',
    rank: '排名',
    invite: '邀请',
    mission: '任务',
    balance: '余额',
    withdraw_upper: '提现',
    weekly_contest: '每周竞赛',
    top_earners: '顶级收入者',
    take_the_prize: '赢得奖品',
    prize_pool: '奖金池',
    today: '今天',
    weekly: '每周',
    monthly: '每月',
    all_time: '全部时间',
    streak: '连续',
    days: '天',
    watch_ads: '观看广告',
    earn_pow: '赚取POW',
    daily_limit: '每日限制',
    watch: '观看',
    watching: '观看中...',
    claim: '领取',
    claimed: '已领取',
    viewing_ads: '观看广告',
    get_paid_watching: '在Telegram上观看短广告即可获得报酬。',
    start_earning: '开始赚钱',
    withdraw: '提现',
    withdrawal: '提现',
    amount: '金额',
    submit: '提交',
    minimum: '最低',
    available: '可用',
    history: '历史',
    pending: '待处理',
    completed: '已完成',
    rejected: '已拒绝',
    checking_requirements: '检查要求...',
    pending_withdrawal_warning: '您有待处理的提现请求，请等待处理。',
    you_will_receive: '您将收到',
    withdrawal_method: '提现方式',
    wallet_activity: '钱包活动',
    no_transactions_yet: '暂无交易',
    withdrawal_history_here: '您的提现历史将显示在这里',
    connect: '连接',
    insufficient_balance: '余额不足',
    requirements_not_met: '未满足要求',
    withdrawal_request_sent: '提现请求已发送。',
    friends: '位朋友',
    friend: '位朋友',
    ads_count: '个广告',
    enter_withdrawal_amount: '输入提现金额',
    withdraw_balance: '提现余额',
    missions: '任务',
    loading: '加载中...',
    error: '错误',
    retry: '重试',
    save: '保存',
    cancel: '取消',
    confirm: '确认',
    success: '成功',
    failed: '失败',
    processing: '处理中...',
    select_language: '选择语言',
    language_changed: '语言已更改！',
  },

  pt: {
    ...baseTranslations,
    settings: 'Configurações',
    language: 'Idioma',
    copied: 'Copiado!',
    close: 'Fechar',
    back: 'Voltar',
    home: 'INÍCIO',
    rank: 'RANKING',
    invite: 'CONVIDAR',
    mission: 'MISSÃO',
    balance: 'SALDO',
    withdraw_upper: 'SACAR',
    weekly_contest: 'CONCURSO SEMANAL',
    top_earners: 'Maiores Ganhadores',
    take_the_prize: 'levam o prêmio',
    prize_pool: 'PRÊMIO TOTAL',
    today: 'Hoje',
    weekly: 'Semanal',
    monthly: 'Mensal',
    all_time: 'Todo o Tempo',
    streak: 'Sequência',
    days: 'dias',
    watch_ads: 'Assistir Anúncios',
    earn_pow: 'Ganhar POW',
    daily_limit: 'Limite Diário',
    watch: 'Assistir',
    watching: 'Assistindo...',
    claim: 'Reivindicar',
    claimed: 'Reivindicado',
    viewing_ads: 'Assistindo Anúncios',
    get_paid_watching: 'Seja pago por assistir anúncios curtos no Telegram.',
    start_earning: 'Começar a Ganhar',
    withdraw: 'Sacar',
    withdrawal: 'Saque',
    amount: 'Valor',
    submit: 'Enviar',
    minimum: 'Mínimo',
    available: 'Disponível',
    history: 'Histórico',
    pending: 'Pendente',
    completed: 'Concluído',
    rejected: 'Rejeitado',
    checking_requirements: 'Verificando requisitos...',
    pending_withdrawal_warning: 'Você tem um saque pendente. Por favor, aguarde o processamento.',
    you_will_receive: 'Você receberá',
    withdrawal_method: 'Método de Saque',
    wallet_activity: 'Atividade da Carteira',
    no_transactions_yet: 'Nenhuma transação ainda',
    withdrawal_history_here: 'Seu histórico de saques aparecerá aqui',
    connect: 'Conectar',
    insufficient_balance: 'Saldo Insuficiente',
    requirements_not_met: 'Requisitos Não Atendidos',
    withdrawal_request_sent: 'Solicitação de saque enviada.',
    friends: 'amigos',
    friend: 'amigo',
    ads_count: 'anúncios',
    enter_withdrawal_amount: 'Digite o Valor do Saque',
    withdraw_balance: 'Sacar Saldo',
    missions: 'Missões',
    loading: 'Carregando...',
    error: 'Erro',
    retry: 'Tentar Novamente',
    save: 'Salvar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    success: 'Sucesso',
    failed: 'Falhou',
    processing: 'Processando...',
    select_language: 'Selecionar Idioma',
    language_changed: 'Idioma alterado!',
  },

  es: {
    ...baseTranslations,
    settings: 'Configuración',
    language: 'Idioma',
    copied: '¡Copiado!',
    close: 'Cerrar',
    back: 'Volver',
    home: 'INICIO',
    rank: 'RANGO',
    invite: 'INVITAR',
    mission: 'MISIÓN',
    balance: 'SALDO',
    withdraw_upper: 'RETIRAR',
    weekly_contest: 'CONCURSO SEMANAL',
    top_earners: 'Mejores Ganadores',
    take_the_prize: 'ganan el premio',
    prize_pool: 'BOTE DE PREMIOS',
    today: 'Hoy',
    weekly: 'Semanal',
    monthly: 'Mensual',
    all_time: 'Todo el Tiempo',
    streak: 'Racha',
    days: 'días',
    watch_ads: 'Ver Anuncios',
    earn_pow: 'Ganar POW',
    daily_limit: 'Límite Diario',
    watch: 'Ver',
    watching: 'Viendo...',
    claim: 'Reclamar',
    claimed: 'Reclamado',
    viewing_ads: 'Viendo Anuncios',
    get_paid_watching: 'Gana dinero por ver anuncios cortos en Telegram.',
    start_earning: 'Empezar a Ganar',
    withdraw: 'Retirar',
    withdrawal: 'Retiro',
    amount: 'Cantidad',
    submit: 'Enviar',
    minimum: 'Mínimo',
    available: 'Disponible',
    history: 'Historial',
    pending: 'Pendiente',
    completed: 'Completado',
    rejected: 'Rechazado',
    checking_requirements: 'Verificando requisitos...',
    pending_withdrawal_warning: 'Tienes un retiro pendiente. Por favor espera a que sea procesado.',
    you_will_receive: 'Recibirás',
    withdrawal_method: 'Método de Retiro',
    wallet_activity: 'Actividad de la Cartera',
    no_transactions_yet: 'Aún no hay transacciones',
    withdrawal_history_here: 'Tu historial de retiros aparecerá aquí',
    connect: 'Conectar',
    insufficient_balance: 'Saldo Insuficiente',
    requirements_not_met: 'Requisitos No Cumplidos',
    withdrawal_request_sent: 'Solicitud de retiro enviada.',
    friends: 'amigos',
    friend: 'amigo',
    ads_count: 'anuncios',
    enter_withdrawal_amount: 'Ingresa el Monto de Retiro',
    withdraw_balance: 'Retirar Saldo',
    missions: 'Misiones',
    loading: 'Cargando...',
    error: 'Error',
    retry: 'Reintentar',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    success: 'Éxito',
    failed: 'Fallido',
    processing: 'Procesando...',
    select_language: 'Seleccionar Idioma',
    language_changed: '¡Idioma cambiado!',
  },

  vi: {
    ...baseTranslations,
    settings: 'Cài đặt',
    language: 'Ngôn ngữ',
    copied: 'Đã sao chép!',
    close: 'Đóng',
    back: 'Quay lại',
    home: 'TRANG CHỦ',
    rank: 'XẾP HẠNG',
    invite: 'MỜI',
    mission: 'NHIỆM VỤ',
    balance: 'SỐ DƯ',
    withdraw_upper: 'RÚT TIỀN',
    weekly_contest: 'THI ĐẤU HÀNG TUẦN',
    top_earners: 'Người Kiếm Nhiều Nhất',
    take_the_prize: 'giành giải thưởng',
    prize_pool: 'QUỸ GIẢI THƯỞNG',
    today: 'Hôm nay',
    weekly: 'Hàng tuần',
    monthly: 'Hàng tháng',
    all_time: 'Mọi thời điểm',
    streak: 'Chuỗi',
    days: 'ngày',
    watch_ads: 'Xem quảng cáo',
    earn_pow: 'Kiếm POW',
    daily_limit: 'Giới hạn hằng ngày',
    watch: 'Xem',
    watching: 'Đang xem...',
    claim: 'Nhận',
    claimed: 'Đã nhận',
    viewing_ads: 'Xem quảng cáo',
    get_paid_watching: 'Kiếm tiền khi xem quảng cáo ngắn trên Telegram.',
    start_earning: 'Bắt đầu kiếm tiền',
    withdraw: 'Rút tiền',
    withdrawal: 'Rút tiền',
    amount: 'Số tiền',
    submit: 'Gửi',
    minimum: 'Tối thiểu',
    available: 'Có sẵn',
    history: 'Lịch sử',
    pending: 'Đang chờ',
    completed: 'Hoàn thành',
    rejected: 'Bị từ chối',
    checking_requirements: 'Kiểm tra yêu cầu...',
    pending_withdrawal_warning: 'Bạn có yêu cầu rút tiền đang chờ xử lý. Vui lòng đợi.',
    you_will_receive: 'Bạn sẽ nhận được',
    withdrawal_method: 'Phương thức rút tiền',
    wallet_activity: 'Hoạt động ví',
    no_transactions_yet: 'Chưa có giao dịch',
    withdrawal_history_here: 'Lịch sử rút tiền của bạn sẽ hiện ở đây',
    connect: 'Kết nối',
    insufficient_balance: 'Số dư không đủ',
    requirements_not_met: 'Chưa đáp ứng yêu cầu',
    withdrawal_request_sent: 'Đã gửi yêu cầu rút tiền.',
    friends: 'bạn bè',
    friend: 'người bạn',
    ads_count: 'quảng cáo',
    enter_withdrawal_amount: 'Nhập số tiền rút',
    withdraw_balance: 'Rút số dư',
    missions: 'Nhiệm vụ',
    loading: 'Đang tải...',
    error: 'Lỗi',
    retry: 'Thử lại',
    save: 'Lưu',
    cancel: 'Hủy',
    confirm: 'Xác nhận',
    success: 'Thành công',
    failed: 'Thất bại',
    processing: 'Đang xử lý...',
    select_language: 'Chọn ngôn ngữ',
    language_changed: 'Đã thay đổi ngôn ngữ!',
  },

  bn: {
    ...baseTranslations,
    settings: 'সেটিংস',
    language: 'ভাষা',
    copied: 'কপি হয়েছে!',
    close: 'বন্ধ',
    back: 'ফিরে যান',
    home: 'হোম',
    rank: 'র্যাংক',
    invite: 'আমন্ত্রণ',
    mission: 'মিশন',
    balance: 'ব্যালেন্স',
    withdraw_upper: 'উত্তোলন',
    weekly_contest: 'সাপ্তাহিক প্রতিযোগিতা',
    top_earners: 'শীর্ষ উপার্জনকারী',
    take_the_prize: 'পুরস্কার নিন',
    prize_pool: 'পুরস্কার ভান্ডার',
    today: 'আজ',
    weekly: 'সাপ্তাহিক',
    monthly: 'মাসিক',
    all_time: 'সর্বকালীন',
    streak: 'ধারা',
    days: 'দিন',
    watch_ads: 'বিজ্ঞাপন দেখুন',
    earn_pow: 'POW উপার্জন করুন',
    daily_limit: 'দৈনিক সীমা',
    watch: 'দেখুন',
    watching: 'দেখছেন...',
    claim: 'দাবি করুন',
    claimed: 'দাবি হয়েছে',
    viewing_ads: 'বিজ্ঞাপন দেখা হচ্ছে',
    get_paid_watching: 'টেলিগ্রামে ছোট বিজ্ঞাপন দেখে অর্থ উপার্জন করুন।',
    start_earning: 'উপার্জন শুরু করুন',
    withdraw: 'উত্তোলন',
    withdrawal: 'উত্তোলন',
    amount: 'পরিমাণ',
    submit: 'জমা দিন',
    minimum: 'সর্বনিম্ন',
    available: 'উপলব্ধ',
    history: 'ইতিহাস',
    pending: 'অপেক্ষমান',
    completed: 'সম্পন্ন',
    rejected: 'প্রত্যাখ্যাত',
    checking_requirements: 'প্রয়োজনীয়তা যাচাই করা হচ্ছে...',
    pending_withdrawal_warning: 'আপনার একটি অপেক্ষমান উত্তোলন আছে। অনুগ্রহ করে প্রক্রিয়াকরণের জন্য অপেক্ষা করুন।',
    you_will_receive: 'আপনি পাবেন',
    withdrawal_method: 'উত্তোলন পদ্ধতি',
    wallet_activity: 'ওয়ালেট কার্যক্রম',
    no_transactions_yet: 'এখনও কোনো লেনদেন নেই',
    withdrawal_history_here: 'আপনার উত্তোলনের ইতিহাস এখানে দেখা যাবে',
    connect: 'সংযুক্ত করুন',
    insufficient_balance: 'অপর্যাপ্ত ব্যালেন্স',
    requirements_not_met: 'প্রয়োজনীয়তা পূরণ হয়নি',
    withdrawal_request_sent: 'উত্তোলনের অনুরোধ পাঠানো হয়েছে।',
    friends: 'বন্ধু',
    friend: 'বন্ধু',
    ads_count: 'বিজ্ঞাপন',
    enter_withdrawal_amount: 'উত্তোলনের পরিমাণ লিখুন',
    withdraw_balance: 'ব্যালেন্স উত্তোলন',
    missions: 'মিশন',
    loading: 'লোড হচ্ছে...',
    error: 'ত্রুটি',
    retry: 'পুনরায় চেষ্টা করুন',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    confirm: 'নিশ্চিত করুন',
    success: 'সফল',
    failed: 'ব্যর্থ',
    processing: 'প্রক্রিয়াকরণ...',
    select_language: 'ভাষা নির্বাচন করুন',
    language_changed: 'ভাষা পরিবর্তন হয়েছে!',
  },
};

export function getTranslation(key: string): string {
  try {
    const saved = localStorage.getItem('app_language') as Language;
    const lang = saved && Object.keys(translations).includes(saved) ? saved : 'en';
    return translations[lang]?.[key] ?? translations['en']?.[key] ?? key;
  } catch {
    return translations['en']?.[key] ?? key;
  }
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
  isRTL: false,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    try {
      const saved = localStorage.getItem('app_language') as Language;
      if (saved && Object.keys(translations).includes(saved)) {
        setLanguageState(saved);
      }
    } catch {}
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('app_language', lang);
    } catch {}
  };

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations['en']?.[key] ?? key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
